import type { Express } from "express";
import { generalLimiter } from "./shared";
import { registerHealthRoutes } from "./health";
import { registerDashboardRoutes } from "./dashboard";
import { registerAlertsRoutes } from "./alerts";
import { registerIncidentsRoutes } from "./incidents";
import { registerConnectorsRoutes } from "./connectors";
import { registerAiRoutes } from "./ai";
import { registerComplianceRoutes } from "./compliance";
import { registerEntitiesRoutes } from "./entities";
import { registerPlaybooksRoutes } from "./playbooks";
import { registerIngestionRoutes } from "./ingestion";
import { registerOperationsRoutes } from "./operations";
import { registerAdminRoutes } from "./admin";
import { registerIntegrationsRoutes } from "./integrations";
import { registerCommercialRoutes } from "./commercial";
import { registerWebhooksRoutes } from "./webhooks";
import { registerReportsRoutes } from "./reports";
import { registerThreatIntelRoutes } from "./threat-intel";
import { registerEndpointsRoutes } from "./endpoints";
import { registerInvestigationsRoutes } from "./investigations";
import { registerOrgsRoutes } from "./orgs";
import { registerOnboardingRoutes } from "./onboarding";
import { registerEventsRoutes } from "./events";
import { registerFilesRoutes } from "./files";
import { registerLifecycleRoutes } from "./lifecycle";
import { registerTenantIsolationRoutes } from "./tenant-isolation";
import { registerEnterpriseOrgRoutes } from "./enterprise-org";
import { registerReportGovernanceRoutes } from "./report-governance";
import { registerApiVersioningRoutes } from "./api-versioning";
import { registerBillingRoutes } from "./billing";
import { registerPasswordResetRoutes } from "./password-reset";
import { registerPlatformAdminRoutes } from "./platform-admin";
import { registerDomainAutoJoinRoutes } from "./domain-autojoin";
import { registerSsoRoutes } from "./sso";
import { registerMsspRoutes } from "./mssp";
import { registerUsageRoutes } from "./usage";
import { registerDevPortalRoutes } from "./dev-portal";
import { registerAutonomousRoutes } from "./autonomous";
import { registerPredictiveRoutes } from "./predictive";
import { registerEngineControlsRoutes } from "./engine-controls";
import { registerEmailTemplateRoutes } from "./email-templates";
import { registerMetricsRollupRoutes } from "./metrics-rollup";
import { registerModelGatewayRoutes } from "./model-gateway";
import { registerPromptArtifactRoutes } from "./prompt-artifact";
import { registerSecurityGraphRoutes } from "./security-graph";
import { registerRemediationRoutes } from "./remediation";
import { registerFindingLineageRoutes } from "./finding-lineage";
import { registerRuntimeGuardrailsRoutes } from "./runtime-guardrails";
import { registerJitSecretAccessRoutes } from "./jit-secret-access";
import { registerIntegrationMarketplaceRoutes } from "./integration-marketplace";
import { registerNativeCollectorRoutes } from "./native-collectors";
import { registerAdversarialTestingRoutes } from "./adversarial-testing";
import { registerSocCopilotRoutes } from "./soc-copilot";
import { registerTieredPackagingRoutes } from "./tiered-packaging";
import { registerTrustCenterRoutes } from "./trust-center";
import { registerPolicyPacksRoutes } from "./policy-packs";
import { registerExecutiveRiskRoutes } from "./executive-risk";
import { registerAgentToolSecurityRoutes } from "./agent-tool-security";
import { registerBrowserDefenseRoutes } from "./browser-defense";
import { registerCrossCuttingRoutes } from "./cross-cutting";
import { registerStunningDashboardRoutes } from "./stunning-dashboard";
import { registerPhase2StubRoutes } from "./phase2-stubs";
import { registerPhase2FeatureRoutes } from "./phase2-features";
import { registerMfaRoutes } from "./mfa";
import { registerTenantDataRoutes } from "./tenant-data";
import { registerWarRoomRoutes } from "./war-room";
import { registerPlaybookTemplateRoutes } from "./playbook-templates";
import { registerInvestigationTimelineRoutes } from "./investigation-timeline";
import { registerEvidenceCustodyRoutes } from "./evidence-custody";
import { registerComplianceGapRoutes } from "./compliance-gap";
import { registerReportSchedulingRoutes } from "./report-scheduling";
import { registerStandalonePlatformRoutes } from "./standalone-platform";
import { registerNativeSensorRoutes } from "./native-sensors";
import { registerLogSourceRoutes } from "./log-sources";
import { registerVulnScannerRoutes } from "./vuln-scanner";
import { registerUebaRoutes } from "./ueba";
import { registerAgentResponseRoutes } from "./agent-response";
import { registerRagKnowledgeRoutes } from "./rag-knowledge";
import { registerSupplyChainRoutes } from "./supply-chain";
import { registerIdentityGovernanceRoutes } from "./identity-governance";
import { registerPamRoutes } from "./pam";
import { registerDeceptionRoutes } from "./deception";
import { registerOtSecurityRoutes } from "./ot-security";
import { registerThreatHuntingRoutes } from "./threat-hunting";
import { registerDataLakeRoutes } from "./data-lake";
import { registerAdvancedReportsRoutes } from "./advanced-reports";
import { registerDataResidencyRoutes } from "./data-residency";
import { registerMobileSecurityRoutes } from "./mobile-security";
import { registerApiSecurityRoutes } from "./api-security";
import { registerRansomwareDefenseRoutes } from "./ransomware-defense";
import { registerCommunityIntelRoutes } from "./community-intel";
import { registerPostureTrustRoutes } from "./posture-trust";
import { registerChaosEngineeringRoutes } from "./chaos-engineering";
import { registerAiDetectionRulesRoutes } from "./ai-detection-rules";
import { registerMsspPortalRoutes } from "./mssp-portal";
import { registerAutonomousSocRoutes } from "./autonomous-soc";
import { registerDeveloperSecurityRoutes } from "./developer-security";
import { registerTprmRoutes } from "./tprm";
import { registerDarkWebRoutes } from "./dark-web";
import { registerPhysicalSecurityRoutes } from "./physical-security";
import { registerSecurityAwarenessRoutes } from "./security-awareness";

export function registerAllDomainRoutes(app: Express): void {
  app.use("/api/", generalLimiter);

  registerHealthRoutes(app);
  registerDashboardRoutes(app);
  registerAlertsRoutes(app);
  registerOnboardingRoutes(app);
  registerIncidentsRoutes(app);
  registerConnectorsRoutes(app);
  registerAiRoutes(app);
  registerIngestionRoutes(app);
  registerEntitiesRoutes(app);
  registerPlaybooksRoutes(app);
  registerReportsRoutes(app);
  registerEventsRoutes(app);
  registerThreatIntelRoutes(app);
  registerComplianceRoutes(app);
  registerIntegrationsRoutes(app);
  registerEndpointsRoutes(app);
  registerInvestigationsRoutes(app);
  registerOperationsRoutes(app);
  registerAdminRoutes(app);
  registerOrgsRoutes(app);
  registerCommercialRoutes(app);
  registerWebhooksRoutes(app);
  registerFilesRoutes(app);
  registerLifecycleRoutes(app);
  registerTenantIsolationRoutes(app);
  registerEnterpriseOrgRoutes(app);
  registerReportGovernanceRoutes(app);
  registerApiVersioningRoutes(app);
  registerBillingRoutes(app);
  registerPasswordResetRoutes(app);
  registerPlatformAdminRoutes(app);
  registerDomainAutoJoinRoutes(app);
  registerSsoRoutes(app);
  registerMsspRoutes(app);
  registerUsageRoutes(app);
  registerDevPortalRoutes(app);
  registerAutonomousRoutes(app);
  registerPredictiveRoutes(app);
  registerEngineControlsRoutes(app);
  registerEmailTemplateRoutes(app);
  registerMetricsRollupRoutes(app);
  registerModelGatewayRoutes(app);
  registerPromptArtifactRoutes(app);
  registerSecurityGraphRoutes(app);
  registerRemediationRoutes(app);
  registerFindingLineageRoutes(app);
  registerRuntimeGuardrailsRoutes(app);
  registerJitSecretAccessRoutes(app);
  registerIntegrationMarketplaceRoutes(app);
  registerNativeCollectorRoutes(app);
  registerAdversarialTestingRoutes(app);
  registerSocCopilotRoutes(app);
  registerTieredPackagingRoutes(app);
  registerTrustCenterRoutes(app);
  registerPolicyPacksRoutes(app);
  registerExecutiveRiskRoutes(app);
  registerAgentToolSecurityRoutes(app);
  registerBrowserDefenseRoutes(app);
  registerCrossCuttingRoutes(app);
  registerStunningDashboardRoutes(app);
  registerPhase2FeatureRoutes(app);
  registerPhase2StubRoutes(app);
  registerMfaRoutes(app);
  registerTenantDataRoutes(app);
  registerWarRoomRoutes(app);
  registerPlaybookTemplateRoutes(app);
  registerInvestigationTimelineRoutes(app);
  registerEvidenceCustodyRoutes(app);
  registerComplianceGapRoutes(app);
  registerReportSchedulingRoutes(app);
  registerStandalonePlatformRoutes(app);
  registerNativeSensorRoutes(app);
  registerLogSourceRoutes(app);
  registerVulnScannerRoutes(app);
  registerUebaRoutes(app);
  registerAgentResponseRoutes(app);
  registerRagKnowledgeRoutes(app);
  registerSupplyChainRoutes(app);
  registerIdentityGovernanceRoutes(app);
  registerPamRoutes(app);
  registerDeceptionRoutes(app);
  registerOtSecurityRoutes(app);
  registerThreatHuntingRoutes(app);
  registerDataLakeRoutes(app);
  registerAdvancedReportsRoutes(app);
  registerDataResidencyRoutes(app);
  registerMobileSecurityRoutes(app);
  registerApiSecurityRoutes(app);
  registerRansomwareDefenseRoutes(app);
  registerCommunityIntelRoutes(app);
  registerPostureTrustRoutes(app);
  registerChaosEngineeringRoutes(app);
  registerAiDetectionRulesRoutes(app);
  registerMsspPortalRoutes(app);
  registerAutonomousSocRoutes(app);
  registerDeveloperSecurityRoutes(app);
  registerTprmRoutes(app);
  registerDarkWebRoutes(app);
  registerPhysicalSecurityRoutes(app);
  registerSecurityAwarenessRoutes(app);
}
