import type { Express } from "express";
import { generalLimiter } from "./shared";
import { registerHealthRoutes } from "./health";
import { registerDashboardRoutes } from "./dashboard";
import { registerAlertsRoutes } from "./alerts";
import { registerIncidentsRoutes } from "./incidents";
import { registerConnectorsRoutes } from "./connectors";
import { registerAiRoutes } from "./ai";
import { registerComplianceRoutes } from "./compliance";
import { registerEntitiesRoutes } from "./entities";
import { registerPlaybooksRoutes } from "./playbooks";
import { registerIngestionRoutes } from "./ingestion";
import { registerOperationsRoutes } from "./operations";
import { registerAdminRoutes } from "./admin";
import { registerIntegrationsRoutes } from "./integrations";
import { registerCommercialRoutes } from "./commercial";
import { registerWebhooksRoutes } from "./webhooks";
import { registerReportsRoutes } from "./reports";
import { registerThreatIntelRoutes } from "./threat-intel";
import { registerEndpointsRoutes } from "./endpoints";
import { registerInvestigationsRoutes } from "./investigations";
import { registerOrgsRoutes } from "./orgs";
import { registerOnboardingRoutes } from "./onboarding";
import { registerEventsRoutes } from "./events";
import { registerFilesRoutes } from "./files";
import { registerLifecycleRoutes } from "./lifecycle";
import { registerTenantIsolationRoutes } from "./tenant-isolation";
import { registerEnterpriseOrgRoutes } from "./enterprise-org";
import { registerReportGovernanceRoutes } from "./report-governance";
import { registerApiVersioningRoutes } from "./api-versioning";
import { registerBillingRoutes } from "./billing";
import { registerPasswordResetRoutes } from "./password-reset";
import { registerPlatformAdminRoutes } from "./platform-admin";
import { registerDomainAutoJoinRoutes } from "./domain-autojoin";
import { registerSsoRoutes } from "./sso";

export function registerAllDomainRoutes(app: Express): void {
  app.use("/api/", generalLimiter);

  registerHealthRoutes(app);
  registerDashboardRoutes(app);
  registerAlertsRoutes(app);
  registerOnboardingRoutes(app);
  registerIncidentsRoutes(app);
  registerConnectorsRoutes(app);
  registerAiRoutes(app);
  registerIngestionRoutes(app);
  registerEntitiesRoutes(app);
  registerPlaybooksRoutes(app);
  registerReportsRoutes(app);
  registerEventsRoutes(app);
  registerThreatIntelRoutes(app);
  registerComplianceRoutes(app);
  registerIntegrationsRoutes(app);
  registerEndpointsRoutes(app);
  registerInvestigationsRoutes(app);
  registerOperationsRoutes(app);
  registerAdminRoutes(app);
  registerOrgsRoutes(app);
  registerCommercialRoutes(app);
  registerWebhooksRoutes(app);
  registerFilesRoutes(app);
  registerLifecycleRoutes(app);
  registerTenantIsolationRoutes(app);
  registerEnterpriseOrgRoutes(app);
  registerReportGovernanceRoutes(app);
  registerApiVersioningRoutes(app);
  registerBillingRoutes(app);
  registerPasswordResetRoutes(app);
  registerPlatformAdminRoutes(app);
  registerDomainAutoJoinRoutes(app);
  registerSsoRoutes(app);
}
