apiVersion: v1
kind: Service
metadata:
  name: securenexus
  namespace: staging
  labels:
    app: securenexus
    environment: staging
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:557845624595:certificate/dc25324b-b238-4041-882e-47ba07965529"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: securenexus
    environment: staging
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
    - port: 443
      targetPort: 5000
      protocol: TCP
      name: https
