/**
 * SecureNexus Built-in Detection Rules
 *
 * 45 pre-built MITRE ATT&CK-mapped detection rules covering the most critical
 * attack techniques. No third-party EDR required — these run on raw sensor events.
 *
 * Coverage:
 *   - Initial Access (T1078, T1133, T1190)
 *   - Execution (T1059, T1053, T1569)
 *   - Persistence (T1547, T1543, T1136)
 *   - Privilege Escalation (T1548, T1055)
 *   - Defense Evasion (T1027, T1562, T1070)
 *   - Credential Access (T1003, T1110, T1552)
 *   - Discovery (T1082, T1083, T1016)
 *   - Lateral Movement (T1021, T1570)
 *   - Collection (T1560, T1005)
 *   - Command & Control (T1071, T1105, T1572)
 *   - Exfiltration (T1041, T1048)
 *   - Impact (T1486, T1489, T1490)
 */

import type { InsertDetectionRule } from "../../shared/schema";
import type { RuleCondition } from "./index";

type BuiltinRule = Omit<InsertDetectionRule, "id" | "createdAt" | "updatedAt"> & {
  conditions: RuleCondition;
};

export const BUILT_IN_RULES: BuiltinRule[] = [
  // ======================================================
  // INITIAL ACCESS
  // ======================================================
  {
    name: "Brute Force Login Detected",
    description: "Multiple consecutive authentication failures from same source — indicates credential brute-forcing.",
    ruleSource: "builtin",
    severity: "high",
    category: "credential_access",
    mitreTactic: "Credential Access",
    mitreTechnique: "Brute Force",
    mitreTechniqueId: "T1110",
    alertTitle: "Brute Force Attack: {username} on {hostname}",
    tags: ["brute-force", "authentication", "initial-access"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["login_failure"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "eventType",
      operator: "equals",
      value: "login_failure",
    },
  },
  {
    name: "SSH Root Login Attempt",
    description: "Direct SSH login attempt as root — high-risk privileged access pattern.",
    ruleSource: "builtin",
    severity: "high",
    category: "credential_access",
    mitreTactic: "Initial Access",
    mitreTechnique: "Valid Accounts",
    mitreTechniqueId: "T1078",
    alertTitle: "SSH Root Login Attempt from {srcIp} on {hostname}",
    tags: ["ssh", "root", "authentication"],
    platforms: ["linux", "macos"],
    eventTypes: ["login_failure", "login_success"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "username", operator: "equals", value: "root" },
        { type: "field", field: "logSource", operator: "contains", value: "sshd" },
      ],
    },
  },

  // ======================================================
  // EXECUTION
  // ======================================================
  {
    name: "PowerShell Encoded Command Execution",
    description: "PowerShell launched with -EncodedCommand or -enc flag — common malware obfuscation technique.",
    ruleSource: "builtin",
    severity: "high",
    category: "malware",
    mitreTactic: "Execution",
    mitreTechnique: "Command and Scripting Interpreter: PowerShell",
    mitreTechniqueId: "T1059.001",
    alertTitle: "Encoded PowerShell Executed on {hostname} by {username}",
    tags: ["powershell", "obfuscation", "execution"],
    platforms: ["windows"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        {
          type: "field",
          field: "processName",
          operator: "regex",
          value: "(?i)powershell(\\.exe)?",
        },
        {
          type: "field",
          field: "rawData.commandLine",
          operator: "regex",
          value: "(?i)(-enc|-encodedcommand|-e\\s)",
        },
      ],
    },
  },
  {
    name: "Suspicious cmd.exe Spawned by Office Application",
    description: "cmd.exe or PowerShell spawned by Word, Excel, or Outlook — classic macro-based initial access.",
    ruleSource: "builtin",
    severity: "critical",
    category: "malware",
    mitreTactic: "Execution",
    mitreTechnique: "User Execution: Malicious File",
    mitreTechniqueId: "T1204.002",
    alertTitle: "Office Application Spawned Shell on {hostname}",
    tags: ["office-macro", "phishing", "execution"],
    platforms: ["windows"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        {
          type: "field",
          field: "parentProcessName",
          operator: "regex",
          value: "(?i)(winword|excel|outlook|powerpnt)\\.exe",
        },
        {
          type: "field",
          field: "processName",
          operator: "regex",
          value: "(?i)(cmd|powershell|wscript|cscript|mshta)\\.exe",
        },
      ],
    },
  },
  {
    name: "Cron Job Created by Non-Root User",
    description: "New cron entry added by a non-privileged user — potential persistence mechanism.",
    ruleSource: "builtin",
    severity: "medium",
    category: "persistence",
    mitreTactic: "Persistence",
    mitreTechnique: "Scheduled Task/Job: Cron",
    mitreTechniqueId: "T1053.003",
    alertTitle: "Cron Job Created by {username} on {hostname}",
    tags: ["cron", "persistence", "scheduled-task"],
    platforms: ["linux", "macos"],
    eventTypes: ["cron_job", "file_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "eventType", operator: "equals", value: "cron_job" },
        { type: "field", field: "username", operator: "not_equals", value: "root" },
      ],
    },
  },
  {
    name: "Bash Reverse Shell Pattern",
    description: "Bash executed with /dev/tcp redirect — classic reverse shell payload.",
    ruleSource: "builtin",
    severity: "critical",
    category: "command_and_control",
    mitreTactic: "Command and Control",
    mitreTechnique: "Non-Application Layer Protocol",
    mitreTechniqueId: "T1095",
    alertTitle: "Reverse Shell Launched on {hostname} by {username}",
    tags: ["reverse-shell", "c2", "bash"],
    platforms: ["linux", "macos"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "rawData.commandLine",
      operator: "regex",
      value: "(?i)/dev/tcp/|bash.*-i.*>&|nc.*-e.*/bin/bash|python.*-c.*socket",
    },
  },
  {
    name: "LOLBIN Execution: certutil",
    description: "certutil.exe used to download files — Living-off-the-Land technique to bypass AV.",
    ruleSource: "builtin",
    severity: "high",
    category: "defense_evasion",
    mitreTactic: "Defense Evasion",
    mitreTechnique: "Signed Binary Proxy Execution",
    mitreTechniqueId: "T1218",
    alertTitle: "LOLBIN certutil Download on {hostname}",
    tags: ["lolbin", "certutil", "download", "defense-evasion"],
    platforms: ["windows"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "processName", operator: "regex", value: "(?i)certutil(\\.exe)?" },
        {
          type: "field",
          field: "rawData.commandLine",
          operator: "regex",
          value: "(?i)(-decode|-urlcache|-f\\s.*http)",
        },
      ],
    },
  },

  // ======================================================
  // PERSISTENCE
  // ======================================================
  {
    name: "New User Account Created",
    description: "A new user account was created — may indicate attacker establishing persistence.",
    ruleSource: "builtin",
    severity: "medium",
    category: "persistence",
    mitreTactic: "Persistence",
    mitreTechnique: "Create Account",
    mitreTechniqueId: "T1136",
    alertTitle: "New User Account Created on {hostname} by {username}",
    tags: ["user-creation", "persistence", "account"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "processName",
      operator: "regex",
      value: "(?i)(useradd|adduser|net\\.exe|net1\\.exe)",
    },
  },
  {
    name: "Service Installed by Non-System User",
    description: "A new Windows service was installed by a non-system account — common persistence vector.",
    ruleSource: "builtin",
    severity: "high",
    category: "persistence",
    mitreTactic: "Persistence",
    mitreTechnique: "Create or Modify System Process: Windows Service",
    mitreTechniqueId: "T1543.003",
    alertTitle: "Suspicious Service Installed on {hostname} by {username}",
    tags: ["service", "persistence", "windows"],
    platforms: ["windows"],
    eventTypes: ["service_install"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "eventType", operator: "equals", value: "service_install" },
        {
          type: "not",
          condition: {
            type: "field",
            field: "username",
            operator: "regex",
            value: "(?i)(system|local service|network service|SYSTEM)",
          },
        },
      ],
    },
  },
  {
    name: "Scheduled Task via schtasks",
    description: "schtasks.exe used to create a scheduled task — persistence or execution technique.",
    ruleSource: "builtin",
    severity: "medium",
    category: "persistence",
    mitreTactic: "Persistence",
    mitreTechnique: "Scheduled Task/Job: Scheduled Task",
    mitreTechniqueId: "T1053.005",
    alertTitle: "Scheduled Task Created on {hostname} by {username}",
    tags: ["scheduled-task", "persistence", "schtasks"],
    platforms: ["windows"],
    eventTypes: ["process_create", "scheduled_task"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "processName", operator: "regex", value: "(?i)schtasks(\\.exe)?" },
        { type: "field", field: "rawData.commandLine", operator: "regex", value: "(?i)/create|/sc|/tr" },
      ],
    },
  },

  // ======================================================
  // PRIVILEGE ESCALATION
  // ======================================================
  {
    name: "Sudo Privilege Escalation",
    description: "sudo command executed to gain root privileges — monitor for unexpected privileged commands.",
    ruleSource: "builtin",
    severity: "medium",
    category: "privilege_escalation",
    mitreTactic: "Privilege Escalation",
    mitreTechnique: "Abuse Elevation Control Mechanism: Sudo and Sudo Caching",
    mitreTechniqueId: "T1548.003",
    alertTitle: "Sudo Executed by {username} on {hostname}",
    tags: ["sudo", "privilege-escalation"],
    platforms: ["linux", "macos"],
    eventTypes: ["process_create", "privilege_escalation"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "or",
      conditions: [
        { type: "field", field: "eventType", operator: "equals", value: "privilege_escalation" },
        { type: "field", field: "processName", operator: "equals", value: "sudo" },
      ],
    },
  },
  {
    name: "Process Injection via ptrace",
    description: "ptrace system call used to inject into another process — common rootkit/RAT technique.",
    ruleSource: "builtin",
    severity: "critical",
    category: "privilege_escalation",
    mitreTactic: "Privilege Escalation",
    mitreTechnique: "Process Injection",
    mitreTechniqueId: "T1055",
    alertTitle: "Process Injection via ptrace on {hostname} by {username}",
    tags: ["ptrace", "process-injection", "privilege-escalation"],
    platforms: ["linux"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "rawData.commandLine",
      operator: "regex",
      value: "(?i)(ptrace|PTRACE_ATTACH|strace.*-p|gdb.*attach)",
    },
  },
  {
    name: "UAC Bypass via fodhelper",
    description: "fodhelper.exe abused to bypass User Account Control — critical Windows PE technique.",
    ruleSource: "builtin",
    severity: "critical",
    category: "privilege_escalation",
    mitreTactic: "Privilege Escalation",
    mitreTechnique: "Abuse Elevation Control Mechanism: Bypass User Account Control",
    mitreTechniqueId: "T1548.002",
    alertTitle: "UAC Bypass via fodhelper on {hostname}",
    tags: ["uac-bypass", "fodhelper", "privilege-escalation"],
    platforms: ["windows"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "parentProcessName", operator: "regex", value: "(?i)fodhelper\\.exe" },
        {
          type: "field",
          field: "processName",
          operator: "regex",
          value: "(?i)(cmd|powershell|mshta|wscript)\\.exe",
        },
      ],
    },
  },

  // ======================================================
  // DEFENSE EVASION
  // ======================================================
  {
    name: "Security Tool Process Killed",
    description: "A common security/AV/EDR process was forcefully terminated — likely defense evasion.",
    ruleSource: "builtin",
    severity: "critical",
    category: "defense_evasion",
    mitreTactic: "Defense Evasion",
    mitreTechnique: "Impair Defenses: Disable or Modify Tools",
    mitreTechniqueId: "T1562.001",
    alertTitle: "Security Tool Killed on {hostname} by {username}",
    tags: ["av-kill", "defense-evasion", "security-tool"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["process_terminate"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "processName",
      operator: "regex",
      value:
        "(?i)(MsMpEng|avast|avg|bitdefender|malwarebytes|eset|kaspersky|cb\\.exe|falconctl|sentinelone|cylance|carbonblack)",
    },
  },
  {
    name: "Windows Defender Disabled via Registry",
    description: "Registry key modification to disable Windows Defender — critical defense evasion.",
    ruleSource: "builtin",
    severity: "critical",
    category: "defense_evasion",
    mitreTactic: "Defense Evasion",
    mitreTechnique: "Impair Defenses: Disable or Modify Tools",
    mitreTechniqueId: "T1562.001",
    alertTitle: "Windows Defender Disabled via Registry on {hostname}",
    tags: ["defender-disable", "registry", "defense-evasion"],
    platforms: ["windows"],
    eventTypes: ["registry_set"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "rawData.registryKey",
      operator: "regex",
      value: "(?i)HKLM.*Windows Defender.*(DisableAntiSpyware|DisableRealtimeMonitoring)",
    },
  },
  {
    name: "Log Clearing via wevtutil",
    description: "Windows event logs cleared using wevtutil — attacker removing forensic evidence.",
    ruleSource: "builtin",
    severity: "high",
    category: "defense_evasion",
    mitreTactic: "Defense Evasion",
    mitreTechnique: "Indicator Removal: Clear Windows Event Logs",
    mitreTechniqueId: "T1070.001",
    alertTitle: "Windows Event Logs Cleared on {hostname} by {username}",
    tags: ["log-clearing", "forensics", "defense-evasion"],
    platforms: ["windows"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "processName", operator: "regex", value: "(?i)wevtutil(\\.exe)?" },
        { type: "field", field: "rawData.commandLine", operator: "regex", value: "(?i)(cl|clear-log)" },
      ],
    },
  },

  // ======================================================
  // CREDENTIAL ACCESS
  // ======================================================
  {
    name: "LSASS Memory Dump Attempt",
    description: "lsass.exe accessed for memory dump — credential harvesting (Mimikatz pattern).",
    ruleSource: "builtin",
    severity: "critical",
    category: "credential_access",
    mitreTactic: "Credential Access",
    mitreTechnique: "OS Credential Dumping: LSASS Memory",
    mitreTechniqueId: "T1003.001",
    alertTitle: "LSASS Memory Dump Attempted on {hostname} by {username}",
    tags: ["lsass", "mimikatz", "credential-dumping"],
    platforms: ["windows"],
    eventTypes: ["process_create", "file_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "or",
      conditions: [
        {
          type: "and",
          conditions: [
            { type: "field", field: "processName", operator: "regex", value: "(?i)(procdump|taskmanager|rundll32)" },
            { type: "field", field: "rawData.commandLine", operator: "regex", value: "(?i)lsass" },
          ],
        },
        {
          type: "field",
          field: "rawData.commandLine",
          operator: "regex",
          value: "(?i)(sekurlsa::logonpasswords|lsadump::sam|mimikatz)",
        },
      ],
    },
  },
  {
    name: "Password Hash Extraction via /etc/shadow",
    description: "Direct read access to /etc/shadow — Linux credential dumping.",
    ruleSource: "builtin",
    severity: "critical",
    category: "credential_access",
    mitreTactic: "Credential Access",
    mitreTechnique: "OS Credential Dumping: /etc/passwd and /etc/shadow",
    mitreTechniqueId: "T1003.008",
    alertTitle: "Shadow File Accessed on {hostname} by {username}",
    tags: ["shadow-file", "credential-dumping", "linux"],
    platforms: ["linux"],
    eventTypes: ["file_create", "file_modify", "process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "or",
      conditions: [
        { type: "field", field: "filePath", operator: "equals", value: "/etc/shadow" },
        { type: "field", field: "rawData.commandLine", operator: "regex", value: "(?i)(cat|less|more|cp).*\\/etc\\/shadow" },
      ],
    },
  },
  {
    name: "Credential Files Accessed in Browser Profiles",
    description: "Access to Chrome/Firefox credential stores — browser credential theft.",
    ruleSource: "builtin",
    severity: "high",
    category: "credential_access",
    mitreTactic: "Credential Access",
    mitreTechnique: "Steal Web Session Cookie",
    mitreTechniqueId: "T1539",
    alertTitle: "Browser Credential Store Accessed on {hostname}",
    tags: ["browser-credentials", "cookies", "credential-access"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["file_create", "file_modify"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "filePath",
      operator: "regex",
      value: "(?i)(Chrome.*Login Data|Firefox.*logins\\.json|Keychain|credential)",
    },
  },

  // ======================================================
  // DISCOVERY
  // ======================================================
  {
    name: "Network Port Scan Detected",
    description: "Rapid outbound connections to many ports — internal or external port scanning activity.",
    ruleSource: "builtin",
    severity: "medium",
    category: "reconnaissance",
    mitreTactic: "Discovery",
    mitreTechnique: "Network Service Discovery",
    mitreTechniqueId: "T1046",
    alertTitle: "Port Scan from {hostname} ({srcIp})",
    tags: ["port-scan", "discovery", "nmap"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "processName",
      operator: "regex",
      value: "(?i)(nmap|masscan|zmap|netdiscover|arp-scan|angry ip)",
    },
  },
  {
    name: "System Enumeration Commands",
    description: "Rapid execution of system enumeration tools — attacker reconnoitering after initial access.",
    ruleSource: "builtin",
    severity: "medium",
    category: "reconnaissance",
    mitreTactic: "Discovery",
    mitreTechnique: "System Information Discovery",
    mitreTechniqueId: "T1082",
    alertTitle: "System Enumeration on {hostname} by {username}",
    tags: ["enumeration", "discovery", "recon"],
    platforms: ["windows"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        {
          type: "field",
          field: "processName",
          operator: "regex",
          value: "(?i)(whoami|net\\.exe|ipconfig|systeminfo|nltest|klist|dsquery)(\\.exe)?",
        },
        {
          type: "not",
          condition: {
            type: "field",
            field: "username",
            operator: "regex",
            value: "(?i)(system|administrator|admin)",
          },
        },
      ],
    },
  },
  {
    name: "Active Directory Enumeration via ldap",
    description: "LDAP queries to enumerate domain users, groups, or computers — common pre-lateral-movement step.",
    ruleSource: "builtin",
    severity: "medium",
    category: "reconnaissance",
    mitreTactic: "Discovery",
    mitreTechnique: "Remote System Discovery",
    mitreTechniqueId: "T1018",
    alertTitle: "AD Enumeration via LDAP on {hostname} by {username}",
    tags: ["ldap", "active-directory", "enumeration"],
    platforms: ["windows"],
    eventTypes: ["network_connect"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "dstPort", operator: "in", value: ["389", "636", "3268", "3269"] },
        {
          type: "not",
          condition: { type: "field", field: "processName", operator: "regex", value: "(?i)(lsass|svchost|mmc)" },
        },
      ],
    },
  },

  // ======================================================
  // LATERAL MOVEMENT
  // ======================================================
  {
    name: "PsExec Remote Execution",
    description: "PsExec or similar tool used for remote code execution — lateral movement technique.",
    ruleSource: "builtin",
    severity: "high",
    category: "lateral_movement",
    mitreTactic: "Lateral Movement",
    mitreTechnique: "Remote Services: SMB/Windows Admin Shares",
    mitreTechniqueId: "T1021.002",
    alertTitle: "PsExec Remote Execution from {hostname} by {username}",
    tags: ["psexec", "lateral-movement", "smb"],
    platforms: ["windows"],
    eventTypes: ["process_create", "service_install"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "or",
      conditions: [
        { type: "field", field: "processName", operator: "regex", value: "(?i)(psexec|psexesvc)(\\.exe)?" },
        {
          type: "and",
          conditions: [
            { type: "field", field: "eventType", operator: "equals", value: "service_install" },
            { type: "field", field: "rawData.serviceName", operator: "regex", value: "(?i)psexec" },
          ],
        },
      ],
    },
  },
  {
    name: "SSH Lateral Movement to Internal Host",
    description: "SSH connection originating from internal host to another internal host — hop-over pattern.",
    ruleSource: "builtin",
    severity: "medium",
    category: "lateral_movement",
    mitreTactic: "Lateral Movement",
    mitreTechnique: "Remote Services: SSH",
    mitreTechniqueId: "T1021.004",
    alertTitle: "SSH Lateral Movement from {hostname} to {dstIp}",
    tags: ["ssh", "lateral-movement"],
    platforms: ["linux", "macos"],
    eventTypes: ["network_connect"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "dstPort", operator: "equals", value: "22" },
        { type: "field", field: "processName", operator: "regex", value: "(?i)(ssh|sshd)(\\.exe)?" },
        {
          type: "not",
          condition: { type: "field", field: "username", operator: "equals", value: "root" },
        },
      ],
    },
  },
  {
    name: "WMI Remote Execution",
    description: "WMIC used for remote command execution — stealthy lateral movement technique.",
    ruleSource: "builtin",
    severity: "high",
    category: "lateral_movement",
    mitreTactic: "Lateral Movement",
    mitreTechnique: "Remote Services: Windows Remote Management",
    mitreTechniqueId: "T1021.006",
    alertTitle: "WMI Remote Execution from {hostname} by {username}",
    tags: ["wmi", "lateral-movement", "wmic"],
    platforms: ["windows"],
    eventTypes: ["process_create", "network_connect"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "processName", operator: "regex", value: "(?i)wmic(\\.exe)?" },
        { type: "field", field: "rawData.commandLine", operator: "regex", value: "(?i)(\\/node:|call|process call create)" },
      ],
    },
  },

  // ======================================================
  // COLLECTION & EXFILTRATION
  // ======================================================
  {
    name: "Data Archive Created with Compression Tool",
    description: "Large archive created by zip/tar/7zip — potential data staging before exfiltration.",
    ruleSource: "builtin",
    severity: "medium",
    category: "data_exfiltration",
    mitreTactic: "Collection",
    mitreTechnique: "Archive Collected Data",
    mitreTechniqueId: "T1560",
    alertTitle: "Data Archiving Detected on {hostname} by {username}",
    tags: ["archiving", "data-staging", "exfiltration"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        {
          type: "field",
          field: "processName",
          operator: "regex",
          value: "(?i)(zip|tar|7z|rar|gzip|compress)(\\.exe)?",
        },
        {
          type: "field",
          field: "rawData.commandLine",
          operator: "regex",
          value: "(?i)(-c|-r|--create|\\/a|archive)",
        },
      ],
    },
  },
  {
    name: "Outbound Data Transfer to Uncommon Port",
    description: "Large outbound network transfer on non-standard port — possible data exfiltration.",
    ruleSource: "builtin",
    severity: "high",
    category: "data_exfiltration",
    mitreTactic: "Exfiltration",
    mitreTechnique: "Exfiltration Over Alternative Protocol",
    mitreTechniqueId: "T1048",
    alertTitle: "Suspicious Outbound Transfer from {hostname} to {dstIp}:{dstPort}",
    tags: ["exfiltration", "data-transfer", "network"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["network_connect"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        {
          type: "not",
          condition: {
            type: "field",
            field: "dstPort",
            operator: "in",
            value: ["80", "443", "22", "21", "25", "53", "8080", "8443"],
          },
        },
        { type: "field", field: "rawData.bytesSent", operator: "gt", value: 1000000 },
      ],
    },
  },
  {
    name: "curl/wget Data Exfiltration",
    description: "curl or wget used to upload data to external server — simple exfiltration technique.",
    ruleSource: "builtin",
    severity: "high",
    category: "data_exfiltration",
    mitreTactic: "Exfiltration",
    mitreTechnique: "Exfiltration Over C2 Channel",
    mitreTechniqueId: "T1041",
    alertTitle: "Data Upload via curl/wget on {hostname} by {username}",
    tags: ["curl", "wget", "exfiltration"],
    platforms: ["linux", "macos", "windows"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "processName", operator: "regex", value: "(?i)(curl|wget)(\\.exe)?" },
        {
          type: "field",
          field: "rawData.commandLine",
          operator: "regex",
          value: "(?i)(-T|--upload-file|-d.*@|--data-binary|--form)",
        },
      ],
    },
  },

  // ======================================================
  // COMMAND & CONTROL
  // ======================================================
  {
    name: "DNS Tunneling Pattern",
    description: "Unusually long DNS queries — indicative of DNS tunneling for C2 communication.",
    ruleSource: "builtin",
    severity: "high",
    category: "command_and_control",
    mitreTactic: "Command and Control",
    mitreTechnique: "Application Layer Protocol: DNS",
    mitreTechniqueId: "T1071.004",
    alertTitle: "DNS Tunneling Detected from {hostname}",
    tags: ["dns-tunneling", "c2", "dns"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["network_dns"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "eventType", operator: "equals", value: "network_dns" },
        { type: "field", field: "rawData.queryLength", operator: "gt", value: 60 },
      ],
    },
  },
  {
    name: "Suspicious Outbound on Port 4444 / 1337 / 31337",
    description: "Outbound connection on classic backdoor/Metasploit default ports.",
    ruleSource: "builtin",
    severity: "critical",
    category: "command_and_control",
    mitreTactic: "Command and Control",
    mitreTechnique: "Non-Standard Port",
    mitreTechniqueId: "T1571",
    alertTitle: "Backdoor Port Connection from {hostname} to {dstIp}",
    tags: ["c2", "metasploit", "backdoor"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["network_connect"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "dstPort",
      operator: "in",
      value: ["4444", "4445", "1337", "31337", "6667", "6666"],
    },
  },
  {
    name: "Tor / Proxy Network Access",
    description: "Connection to known Tor or proxy infrastructure — C2 channel obfuscation.",
    ruleSource: "builtin",
    severity: "high",
    category: "command_and_control",
    mitreTactic: "Command and Control",
    mitreTechnique: "Proxy",
    mitreTechniqueId: "T1090",
    alertTitle: "Tor/Proxy Connection from {hostname}",
    tags: ["tor", "proxy", "c2"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["process_create", "network_connect"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "or",
      conditions: [
        { type: "field", field: "processName", operator: "regex", value: "(?i)(tor\\.exe|torbrowser|proxifier)" },
        { type: "field", field: "dstPort", operator: "in", value: ["9050", "9051", "9150"] },
      ],
    },
  },

  // ======================================================
  // IMPACT
  // ======================================================
  {
    name: "Ransomware File Extension Modification",
    description: "Mass file renaming to ransomware-typical extensions — critical ransomware activity.",
    ruleSource: "builtin",
    severity: "critical",
    category: "malware",
    mitreTactic: "Impact",
    mitreTechnique: "Data Encrypted for Impact",
    mitreTechniqueId: "T1486",
    alertTitle: "Ransomware Encryption Activity on {hostname}",
    tags: ["ransomware", "encryption", "impact"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["file_rename", "file_modify"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "filePath",
      operator: "regex",
      value: "(?i)\\.(locked|encrypted|enc|ransom|crypt|wncry|wannacry|petya|locky|cerber|ryuk|darkside)",
    },
  },
  {
    name: "System Backup Deletion",
    description: "Shadow copies or system backups deleted — ransomware preventing recovery.",
    ruleSource: "builtin",
    severity: "critical",
    category: "malware",
    mitreTactic: "Impact",
    mitreTechnique: "Inhibit System Recovery",
    mitreTechniqueId: "T1490",
    alertTitle: "Backup Deletion Attempted on {hostname} by {username}",
    tags: ["backup-deletion", "ransomware", "shadow-copy"],
    platforms: ["windows"],
    eventTypes: ["process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "or",
      conditions: [
        {
          type: "and",
          conditions: [
            { type: "field", field: "processName", operator: "regex", value: "(?i)vssadmin(\\.exe)?" },
            { type: "field", field: "rawData.commandLine", operator: "regex", value: "(?i)(delete|resize)" },
          ],
        },
        {
          type: "and",
          conditions: [
            { type: "field", field: "processName", operator: "regex", value: "(?i)wmic(\\.exe)?" },
            { type: "field", field: "rawData.commandLine", operator: "regex", value: "(?i)shadowcopy.*delete" },
          ],
        },
      ],
    },
  },

  // ======================================================
  // CLOUD / CONTAINER SPECIFIC
  // ======================================================
  {
    name: "Docker Socket Accessed from Container",
    description: "Container accessing the Docker daemon socket — privilege escalation or escape attempt.",
    ruleSource: "builtin",
    severity: "critical",
    category: "privilege_escalation",
    mitreTactic: "Privilege Escalation",
    mitreTechnique: "Escape to Host",
    mitreTechniqueId: "T1611",
    alertTitle: "Docker Socket Access from Container on {hostname}",
    tags: ["container-escape", "docker", "privilege-escalation"],
    platforms: ["linux", "docker"],
    eventTypes: ["file_create", "process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "or",
      conditions: [
        { type: "field", field: "filePath", operator: "contains", value: "/var/run/docker.sock" },
        {
          type: "field",
          field: "rawData.commandLine",
          operator: "regex",
          value: "(?i)(docker.*-H|curl.*\\/var\\/run\\/docker.sock)",
        },
      ],
    },
  },
  {
    name: "Kubernetes Service Account Token Read",
    description: "Service account token accessed from a pod — potential credential theft in Kubernetes.",
    ruleSource: "builtin",
    severity: "high",
    category: "credential_access",
    mitreTactic: "Credential Access",
    mitreTechnique: "Steal Application Access Token",
    mitreTechniqueId: "T1528",
    alertTitle: "K8s Service Account Token Read on {hostname}",
    tags: ["kubernetes", "token-theft", "credential-access"],
    platforms: ["linux", "kubernetes"],
    eventTypes: ["file_create", "process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "or",
      conditions: [
        {
          type: "field",
          field: "filePath",
          operator: "contains",
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token",
        },
        {
          type: "field",
          field: "rawData.commandLine",
          operator: "regex",
          value: "(?i)(cat|less|curl).*serviceaccount.*token",
        },
      ],
    },
  },
  {
    name: "Cryptominer Detected",
    description: "Known cryptominer binary or pool connection detected — resource hijacking.",
    ruleSource: "builtin",
    severity: "high",
    category: "malware",
    mitreTactic: "Impact",
    mitreTechnique: "Resource Hijacking",
    mitreTechniqueId: "T1496",
    alertTitle: "Cryptominer Activity on {hostname}",
    tags: ["cryptominer", "xmrig", "impact"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["process_create", "network_connect"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "or",
      conditions: [
        {
          type: "field",
          field: "processName",
          operator: "regex",
          value: "(?i)(xmrig|minerd|cpuminer|ethminer|cgminer|bfgminer)",
        },
        {
          type: "field",
          field: "dstIp",
          operator: "regex",
          value: "(?i)(pool\\.minexmr|xmrpool|supportxmr|nanopool|f2pool)",
        },
        {
          type: "field",
          field: "rawData.commandLine",
          operator: "regex",
          value: "(?i)(stratum\\+tcp|mining|pool\\..*:3333|pool\\..*:4444)",
        },
      ],
    },
  },

  // ======================================================
  // WEB APPLICATION / LOG INGESTION RULES
  // ======================================================
  {
    name: "SQL Injection Attempt in Web Logs",
    description: "SQL injection pattern detected in HTTP request — web application attack.",
    ruleSource: "builtin",
    severity: "high",
    category: "intrusion",
    mitreTactic: "Initial Access",
    mitreTechnique: "Exploit Public-Facing Application",
    mitreTechniqueId: "T1190",
    alertTitle: "SQL Injection Attempt on {hostname}",
    tags: ["sqli", "web-attack", "initial-access"],
    platforms: ["linux", "windows"],
    eventTypes: ["log_line"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "rawLog",
      operator: "regex",
      value: "(?i)(union.*select|'.*or.*'='|1=1|drop.*table|insert.*into|select.*from.*where|xp_cmdshell)",
    },
  },
  {
    name: "SSH Successful Login from New Country",
    description: "Successful SSH login from an IP geolocation not previously seen — account compromise indicator.",
    ruleSource: "builtin",
    severity: "medium",
    category: "intrusion",
    mitreTactic: "Initial Access",
    mitreTechnique: "Valid Accounts",
    mitreTechniqueId: "T1078",
    alertTitle: "SSH Login from Unknown Location to {hostname}",
    tags: ["geo-anomaly", "ssh", "account-compromise"],
    platforms: ["linux", "macos"],
    eventTypes: ["login_success"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        { type: "field", field: "eventType", operator: "equals", value: "login_success" },
        { type: "field", field: "logSource", operator: "contains", value: "sshd" },
        { type: "field", field: "srcIp", operator: "exists" },
      ],
    },
  },
  {
    name: "Package Manager Running as Unexpected User",
    description: "apt/yum/dnf/pip run by a non-privileged user — potential unauthorized software installation.",
    ruleSource: "builtin",
    severity: "medium",
    category: "persistence",
    mitreTactic: "Persistence",
    mitreTechnique: "Supply Chain Compromise",
    mitreTechniqueId: "T1195",
    alertTitle: "Unauthorized Package Installation on {hostname} by {username}",
    tags: ["package-manager", "supply-chain", "persistence"],
    platforms: ["linux"],
    eventTypes: ["process_create", "package_install"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        {
          type: "field",
          field: "processName",
          operator: "regex",
          value: "(?i)(apt|apt-get|yum|dnf|zypper|pip|pip3|npm|gem)",
        },
        { type: "field", field: "username", operator: "not_equals", value: "root" },
        {
          type: "field",
          field: "rawData.commandLine",
          operator: "regex",
          value: "(?i)(install|upgrade|update)",
        },
      ],
    },
  },

  // ======================================================
  // NETWORK ANOMALIES
  // ======================================================
  {
    name: "Outbound Connection to Known Malicious IP",
    description: "Network connection to an IP flagged in threat intelligence feeds.",
    ruleSource: "builtin",
    severity: "critical",
    category: "command_and_control",
    mitreTactic: "Command and Control",
    mitreTechnique: "Application Layer Protocol",
    mitreTechniqueId: "T1071",
    alertTitle: "Malicious IP Connection from {hostname} to {dstIp}",
    tags: ["threat-intel", "c2", "malicious-ip"],
    platforms: ["windows", "linux", "macos"],
    eventTypes: ["network_connect"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "rawData.isThreatIntelMatch",
      operator: "equals",
      value: "true",
    },
  },
  {
    name: "Unusual Inbound Port Access on Database Server",
    description: "Database port accessed from unexpected source — potential unauthorized DB access.",
    ruleSource: "builtin",
    severity: "high",
    category: "intrusion",
    mitreTactic: "Collection",
    mitreTechnique: "Data from Information Repositories",
    mitreTechniqueId: "T1213",
    alertTitle: "Database Port Accessed from {srcIp} on {hostname}",
    tags: ["database", "unauthorized-access"],
    platforms: ["linux", "windows"],
    eventTypes: ["network_connect", "network_listen"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "and",
      conditions: [
        {
          type: "field",
          field: "dstPort",
          operator: "in",
          value: ["3306", "5432", "1433", "1521", "27017", "6379", "9200"],
        },
        { type: "field", field: "srcIp", operator: "exists" },
        {
          type: "not",
          condition: {
            type: "field",
            field: "srcIp",
            operator: "regex",
            value: "^(10\\.|172\\.(1[6-9]|2[0-9]|3[01])\\.|192\\.168\\.)",
          },
        },
      ],
    },
  },

  // ======================================================
  // FILE SYSTEM INTEGRITY
  // ======================================================
  {
    name: "SUID/SGID Binary Modified",
    description: "SUID or SGID bit set on a file — classic privilege escalation persistence on Linux.",
    ruleSource: "builtin",
    severity: "high",
    category: "privilege_escalation",
    mitreTactic: "Privilege Escalation",
    mitreTechnique: "Abuse Elevation Control Mechanism: Setuid and Setgid",
    mitreTechniqueId: "T1548.001",
    alertTitle: "SUID Binary Created/Modified on {hostname} by {username}",
    tags: ["suid", "sgid", "privilege-escalation"],
    platforms: ["linux", "macos"],
    eventTypes: ["file_modify", "file_create", "process_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "or",
      conditions: [
        {
          type: "and",
          conditions: [
            { type: "field", field: "processName", operator: "equals", value: "chmod" },
            {
              type: "field",
              field: "rawData.commandLine",
              operator: "regex",
              value: "(?i)(\\+s|4[0-7]{3}|6[0-7]{3}|u\\+s|g\\+s)",
            },
          ],
        },
        { type: "field", field: "rawData.modeChange", operator: "regex", value: "(suid|sgid)" },
      ],
    },
  },
  {
    name: "Critical System Binary Modified",
    description: "Core system binary overwritten — potential rootkit installation or supply chain attack.",
    ruleSource: "builtin",
    severity: "critical",
    category: "defense_evasion",
    mitreTactic: "Defense Evasion",
    mitreTechnique: "Modify System Image",
    mitreTechniqueId: "T1601",
    alertTitle: "Critical System Binary Modified on {hostname}",
    tags: ["rootkit", "supply-chain", "binary-modification"],
    platforms: ["linux", "macos"],
    eventTypes: ["file_modify", "file_create"],
    status: "active",
    isBuiltin: true,
    isCommunity: false,
    version: 1,
    conditions: {
      type: "field",
      field: "filePath",
      operator: "regex",
      value: "^(/bin/|/sbin/|/usr/bin/|/usr/sbin/|/lib/|/usr/lib/)(ssh|ls|ps|netstat|top|bash|sh|python|curl|wget)",
    },
  },
];

export function getBuiltInRuleCount(): number {
  return BUILT_IN_RULES.length;
}
