// Barrel index for server/storage/ -- auto-generated
// Re-exports IStorage interface and DatabaseStorage class

export type { IStorage } from "./types";

import * as alertsFns from "./alerts";
import * as incidentsFns from "./incidents";
import * as connectorsFns from "./connectors";
import * as organizationsFns from "./organizations";
import * as authFns from "./auth";
import * as playbooksFns from "./playbooks";
import * as complianceFns from "./compliance";
import * as aiFns from "./ai";
import * as iocFns from "./ioc";
import * as cspmFns from "./cspm";
import * as dashboardFns from "./dashboard";
import * as predictiveFns from "./predictive";
import * as jobsFns from "./jobs";
import * as responseActionsFns from "./response-actions";
import * as reportsFns from "./reports";
import * as billingFns from "./billing";
import * as warRoomFns from "./war-room";
import * as evidenceFns from "./evidence";
import * as auditFns from "./audit";
import * as notificationsFns from "./notifications";
import * as miscFns from "./misc";
import * as sensorsFns from "./sensors";
import * as darkWebFns from "./dark-web";
import * as collectorsFns from "./collectors";
import * as chaosFns from "./chaos";
import * as dnsFns from "./dns";
import * as securityGraphFns from "./security-graph";
import * as trustCenterFns from "./trust-center";
import * as policyPacksFns from "./policy-packs";
import * as marketplaceFns from "./marketplace";
import * as crossCuttingFns from "./cross-cutting";
import * as jitAccessFns from "./jit-access";
import * as adversarialTestingFns from "./adversarial-testing";
import * as agentToolSecurityFns from "./agent-tool-security";
import * as browserDefenseFns from "./browser-defense";
import * as runtimeGuardrailsFns from "./runtime-guardrails";
import * as complianceGapFns from "./compliance-gap";

import type { IStorage } from "./types";

export class DatabaseStorage implements IStorage {
  // alerts
  getAlerts = alertsFns.getAlerts;
  getAlert = alertsFns.getAlert;
  createAlert = alertsFns.createAlert;
  updateAlertStatus = alertsFns.updateAlertStatus;
  updateAlert = alertsFns.updateAlert;
  searchAlerts = alertsFns.searchAlerts;
  getAlertsByIncident = alertsFns.getAlertsByIncident;
  findAlertByDedup = alertsFns.findAlertByDedup;
  upsertAlert = alertsFns.upsertAlert;
  getAlertsPaginated = alertsFns.getAlertsPaginated;
  getAlertsPaginatedWithSort = alertsFns.getAlertsPaginatedWithSort;
  getAlertTags = alertsFns.getAlertTags;
  addAlertTag = alertsFns.addAlertTag;
  removeAlertTag = alertsFns.removeAlertTag;
  getAlertDedupClusters = alertsFns.getAlertDedupClusters;
  getAlertDedupCluster = alertsFns.getAlertDedupCluster;
  createAlertDedupCluster = alertsFns.createAlertDedupCluster;
  updateAlertDedupCluster = alertsFns.updateAlertDedupCluster;
  getAlertDailyStats = alertsFns.getAlertDailyStats;
  upsertAlertDailyStat = alertsFns.upsertAlertDailyStat;
  getArchivedAlerts = alertsFns.getArchivedAlerts;
  getArchivedAlertCount = alertsFns.getArchivedAlertCount;
  archiveAlerts = alertsFns.archiveAlerts;
  restoreArchivedAlerts = alertsFns.restoreArchivedAlerts;
  deleteArchivedAlerts = alertsFns.deleteArchivedAlerts;

  // incidents
  getIncidents = incidentsFns.getIncidents;
  getIncident = incidentsFns.getIncident;
  createIncident = incidentsFns.createIncident;
  updateIncident = incidentsFns.updateIncident;
  getIncidentsPaginated = incidentsFns.getIncidentsPaginated;
  getIncidentsPaginatedWithSort = incidentsFns.getIncidentsPaginatedWithSort;
  getComments = incidentsFns.getComments;
  createComment = incidentsFns.createComment;
  deleteComment = incidentsFns.deleteComment;
  getIncidentTags = incidentsFns.getIncidentTags;
  addIncidentTag = incidentsFns.addIncidentTag;
  removeIncidentTag = incidentsFns.removeIncidentTag;
  getIncidentSlaPolicies = incidentsFns.getIncidentSlaPolicies;
  getIncidentSlaPolicy = incidentsFns.getIncidentSlaPolicy;
  createIncidentSlaPolicy = incidentsFns.createIncidentSlaPolicy;
  updateIncidentSlaPolicy = incidentsFns.updateIncidentSlaPolicy;
  deleteIncidentSlaPolicy = incidentsFns.deleteIncidentSlaPolicy;
  getPostIncidentReviews = incidentsFns.getPostIncidentReviews;
  getPostIncidentReview = incidentsFns.getPostIncidentReview;
  createPostIncidentReview = incidentsFns.createPostIncidentReview;
  updatePostIncidentReview = incidentsFns.updatePostIncidentReview;
  deletePostIncidentReview = incidentsFns.deletePostIncidentReview;
  getPirActionItems = incidentsFns.getPirActionItems;
  getPirActionItem = incidentsFns.getPirActionItem;
  createPirActionItem = incidentsFns.createPirActionItem;
  updatePirActionItem = incidentsFns.updatePirActionItem;
  deletePirActionItem = incidentsFns.deletePirActionItem;
  getIncidentResponseApprovals = incidentsFns.getIncidentResponseApprovals;
  getIncidentResponseApproval = incidentsFns.getIncidentResponseApproval;
  createIncidentResponseApproval = incidentsFns.createIncidentResponseApproval;
  updateIncidentResponseApproval = incidentsFns.updateIncidentResponseApproval;

  // connectors
  getConnectors = connectorsFns.getConnectors;
  getConnectorsPaginated = connectorsFns.getConnectorsPaginated;
  getConnectorsPaginatedWithSort = connectorsFns.getConnectorsPaginatedWithSort;
  getConnector = connectorsFns.getConnector;
  createConnector = connectorsFns.createConnector;
  updateConnector = connectorsFns.updateConnector;
  deleteConnector = connectorsFns.deleteConnector;
  updateConnectorSyncStatus = connectorsFns.updateConnectorSyncStatus;
  createConnectorJobRun = connectorsFns.createConnectorJobRun;
  updateConnectorJobRun = connectorsFns.updateConnectorJobRun;
  getConnectorJobRuns = connectorsFns.getConnectorJobRuns;
  getDeadLetterJobRuns = connectorsFns.getDeadLetterJobRuns;
  getDeadLetterJobRunsPaginated = connectorsFns.getDeadLetterJobRunsPaginated;
  getConnectorJobRunById = connectorsFns.getConnectorJobRunById;
  getOrgAdminEmails = connectorsFns.getOrgAdminEmails;
  getConnectorMetrics = connectorsFns.getConnectorMetrics;
  createConnectorHealthCheck = connectorsFns.createConnectorHealthCheck;
  getConnectorHealthChecks = connectorsFns.getConnectorHealthChecks;
  getLatestHealthCheck = connectorsFns.getLatestHealthCheck;
  getConnectorSecretRotations = connectorsFns.getConnectorSecretRotations;
  createConnectorSecretRotation = connectorsFns.createConnectorSecretRotation;
  updateConnectorSecretRotation = connectorsFns.updateConnectorSecretRotation;
  getExpiringSecretRotations = connectorsFns.getExpiringSecretRotations;

  // organizations
  getOrganizations = organizationsFns.getOrganizations;
  getOrganization = organizationsFns.getOrganization;
  createOrganization = organizationsFns.createOrganization;
  updateOrganization = organizationsFns.updateOrganization;
  softDeleteOrganization = organizationsFns.softDeleteOrganization;
  getOrganizationBySlug = organizationsFns.getOrganizationBySlug;
  getVerifiedAutoJoinDomain = organizationsFns.getVerifiedAutoJoinDomain;
  getOrgMemberships = organizationsFns.getOrgMemberships;
  getOrgMembership = organizationsFns.getOrgMembership;
  getMembershipById = organizationsFns.getMembershipById;
  getUserMemberships = organizationsFns.getUserMemberships;
  createOrgMembership = organizationsFns.createOrgMembership;
  updateOrgMembership = organizationsFns.updateOrgMembership;
  transferOwnership = organizationsFns.transferOwnership;
  deleteOrgMembership = organizationsFns.deleteOrgMembership;
  getOrgInvitations = organizationsFns.getOrgInvitations;
  getOrgInvitationByToken = organizationsFns.getOrgInvitationByToken;
  getPendingInvitationsByEmail = organizationsFns.getPendingInvitationsByEmail;
  createOrgInvitation = organizationsFns.createOrgInvitation;
  updateOrgInvitation = organizationsFns.updateOrgInvitation;
  deleteOrgInvitation = organizationsFns.deleteOrgInvitation;
  getOrgSecurityPolicy = organizationsFns.getOrgSecurityPolicy;
  upsertOrgSecurityPolicy = organizationsFns.upsertOrgSecurityPolicy;
  getOrgDomainVerifications = organizationsFns.getOrgDomainVerifications;
  getOrgDomainVerification = organizationsFns.getOrgDomainVerification;
  createOrgDomainVerification = organizationsFns.createOrgDomainVerification;
  updateOrgDomainVerification = organizationsFns.updateOrgDomainVerification;
  deleteOrgDomainVerification = organizationsFns.deleteOrgDomainVerification;
  getOrgSsoConfig = organizationsFns.getOrgSsoConfig;
  upsertOrgSsoConfig = organizationsFns.upsertOrgSsoConfig;
  deleteOrgSsoConfig = organizationsFns.deleteOrgSsoConfig;
  getOrgScimConfig = organizationsFns.getOrgScimConfig;
  upsertOrgScimConfig = organizationsFns.upsertOrgScimConfig;
  deleteOrgScimConfig = organizationsFns.deleteOrgScimConfig;
  getOrgPlanLimit = organizationsFns.getOrgPlanLimit;
  upsertOrgPlanLimit = organizationsFns.upsertOrgPlanLimit;
  updateOrgPlanLimit = organizationsFns.updateOrgPlanLimit;
  getOnboardingProgress = organizationsFns.getOnboardingProgress;
  upsertOnboardingStep = organizationsFns.upsertOnboardingStep;
  completeOnboardingStep = organizationsFns.completeOnboardingStep;
  getWorkspaceTemplates = organizationsFns.getWorkspaceTemplates;
  getWorkspaceTemplate = organizationsFns.getWorkspaceTemplate;
  createWorkspaceTemplate = organizationsFns.createWorkspaceTemplate;
  getWizardProgress = organizationsFns.getWizardProgress;
  upsertWizardProgress = organizationsFns.upsertWizardProgress;
  updateWizardProgress = organizationsFns.updateWizardProgress;
  getChildOrganizations = organizationsFns.getChildOrganizations;
  createMsspAccessGrant = organizationsFns.createMsspAccessGrant;
  getMsspAccessGrants = organizationsFns.getMsspAccessGrants;
  getMsspAccessGrant = organizationsFns.getMsspAccessGrant;
  revokeMsspAccessGrant = organizationsFns.revokeMsspAccessGrant;
  getMsspAggregatedStats = organizationsFns.getMsspAggregatedStats;
  countUserActiveSessions = organizationsFns.countUserActiveSessions;
  evictOldestUserSessions = organizationsFns.evictOldestUserSessions;

  // auth
  createApiKey = authFns.createApiKey;
  getApiKeys = authFns.getApiKeys;
  getApiKeyByHash = authFns.getApiKeyByHash;
  getApiKeyById = authFns.getApiKeyById;
  revokeApiKey = authFns.revokeApiKey;
  deprecateApiKey = authFns.deprecateApiKey;
  updateApiKeyLastUsed = authFns.updateApiKeyLastUsed;
  createPasswordResetToken = authFns.createPasswordResetToken;
  getPasswordResetToken = authFns.getPasswordResetToken;
  markPasswordResetTokenAsUsed = authFns.markPasswordResetTokenAsUsed;
  consumePasswordResetToken = authFns.consumePasswordResetToken;
  invalidateAllUserPasswordResetTokens = authFns.invalidateAllUserPasswordResetTokens;
  deleteExpiredPasswordResetTokens = authFns.deleteExpiredPasswordResetTokens;
  getIdempotencyKey = authFns.getIdempotencyKey;
  createIdempotencyKey = authFns.createIdempotencyKey;
  cleanupExpiredIdempotencyKeys = authFns.cleanupExpiredIdempotencyKeys;

  // playbooks
  getPlaybooks = playbooksFns.getPlaybooks;
  getPlaybook = playbooksFns.getPlaybook;
  createPlaybook = playbooksFns.createPlaybook;
  updatePlaybook = playbooksFns.updatePlaybook;
  deletePlaybook = playbooksFns.deletePlaybook;
  getPlaybookExecutions = playbooksFns.getPlaybookExecutions;
  countPlaybookExecutionsByOrg = playbooksFns.countPlaybookExecutionsByOrg;
  getPlaybookExecution = playbooksFns.getPlaybookExecution;
  createPlaybookExecution = playbooksFns.createPlaybookExecution;
  updatePlaybookExecution = playbooksFns.updatePlaybookExecution;
  getPlaybookApprovals = playbooksFns.getPlaybookApprovals;
  getPlaybookApproval = playbooksFns.getPlaybookApproval;
  getPlaybookApprovalsByExecution = playbooksFns.getPlaybookApprovalsByExecution;
  createPlaybookApproval = playbooksFns.createPlaybookApproval;
  updatePlaybookApproval = playbooksFns.updatePlaybookApproval;
  getPlaybookVersions = playbooksFns.getPlaybookVersions;
  getPlaybookVersion = playbooksFns.getPlaybookVersion;
  getLatestPlaybookVersion = playbooksFns.getLatestPlaybookVersion;
  createPlaybookVersion = playbooksFns.createPlaybookVersion;
  updatePlaybookVersion = playbooksFns.updatePlaybookVersion;
  getBlastRadiusPreviews = playbooksFns.getBlastRadiusPreviews;
  getBlastRadiusPreview = playbooksFns.getBlastRadiusPreview;
  createBlastRadiusPreview = playbooksFns.createBlastRadiusPreview;
  getPlaybookSimulations = playbooksFns.getPlaybookSimulations;
  getPlaybookSimulation = playbooksFns.getPlaybookSimulation;
  createPlaybookSimulation = playbooksFns.createPlaybookSimulation;
  updatePlaybookSimulation = playbooksFns.updatePlaybookSimulation;
  getPlaybookRollbackPlans = playbooksFns.getPlaybookRollbackPlans;
  getPlaybookRollbackPlan = playbooksFns.getPlaybookRollbackPlan;
  createPlaybookRollbackPlan = playbooksFns.createPlaybookRollbackPlan;
  updatePlaybookRollbackPlan = playbooksFns.updatePlaybookRollbackPlan;

  // compliance
  getCompliancePolicy = complianceFns.getCompliancePolicy;
  upsertCompliancePolicy = complianceFns.upsertCompliancePolicy;
  getComplianceGapAssessments = complianceGapFns.getComplianceGapAssessments;
  getComplianceGapAssessment = complianceGapFns.getComplianceGapAssessment;
  getComplianceGapsByFramework = complianceGapFns.getComplianceGapsByFramework;
  createComplianceGapAssessment = complianceGapFns.createComplianceGapAssessment;
  getDsarRequests = complianceFns.getDsarRequests;
  getDsarRequest = complianceFns.getDsarRequest;
  createDsarRequest = complianceFns.createDsarRequest;
  updateDsarRequest = complianceFns.updateDsarRequest;
  getPolicyChecks = complianceFns.getPolicyChecks;
  getPolicyCheck = complianceFns.getPolicyCheck;
  getPolicyCheckForOrg = complianceFns.getPolicyCheckForOrg;
  createPolicyCheck = complianceFns.createPolicyCheck;
  updatePolicyCheck = complianceFns.updatePolicyCheck;
  deletePolicyCheck = complianceFns.deletePolicyCheck;
  getPolicyResults = complianceFns.getPolicyResults;
  createPolicyResult = complianceFns.createPolicyResult;
  deletePolicyResult = complianceFns.deletePolicyResult;
  getComplianceControls = complianceFns.getComplianceControls;
  getComplianceControl = complianceFns.getComplianceControl;
  createComplianceControl = complianceFns.createComplianceControl;
  createComplianceControls = complianceFns.createComplianceControls;
  updateComplianceControl = complianceFns.updateComplianceControl;
  deleteComplianceControl = complianceFns.deleteComplianceControl;
  getComplianceControlMappings = complianceFns.getComplianceControlMappings;
  createComplianceControlMapping = complianceFns.createComplianceControlMapping;
  updateComplianceControlMapping = complianceFns.updateComplianceControlMapping;
  deleteComplianceControlMapping = complianceFns.deleteComplianceControlMapping;
  getEvidenceLockerItems = complianceFns.getEvidenceLockerItems;
  getEvidenceLockerItem = complianceFns.getEvidenceLockerItem;
  createEvidenceLockerItem = complianceFns.createEvidenceLockerItem;
  updateEvidenceLockerItem = complianceFns.updateEvidenceLockerItem;
  deleteEvidenceLockerItem = complianceFns.deleteEvidenceLockerItem;
  getLegalHolds = complianceFns.getLegalHolds;
  getLegalHold = complianceFns.getLegalHold;
  createLegalHold = complianceFns.createLegalHold;
  updateLegalHold = complianceFns.updateLegalHold;
  getEvidenceAttachments = complianceFns.getEvidenceAttachments;
  getEvidenceAttachment = complianceFns.getEvidenceAttachment;
  createEvidenceAttachment = complianceFns.createEvidenceAttachment;
  updateEvidenceAttachment = complianceFns.updateEvidenceAttachment;
  deleteEvidenceAttachment = complianceFns.deleteEvidenceAttachment;
  getComplianceControlHelpers = complianceFns.getComplianceControlHelpers;
  getComplianceControlHelper = complianceFns.getComplianceControlHelper;
  createComplianceControlHelper = complianceFns.createComplianceControlHelper;
  updateComplianceControlHelper = complianceFns.updateComplianceControlHelper;

  // ai
  createAiFeedback = aiFns.createAiFeedback;
  getAiFeedback = aiFns.getAiFeedback;
  countAiFeedbackByOrg = aiFns.countAiFeedbackByOrg;
  getAiFeedbackMetrics = aiFns.getAiFeedbackMetrics;
  getAiFeedbackByResource = aiFns.getAiFeedbackByResource;
  getAiDeploymentConfig = aiFns.getAiDeploymentConfig;
  upsertAiDeploymentConfig = aiFns.upsertAiDeploymentConfig;
  createChatMessage = aiFns.createChatMessage;
  getChatThread = aiFns.getChatThread;
  getChatThreadsByIncident = aiFns.getChatThreadsByIncident;
  createAiGeneratedRule = aiFns.createAiGeneratedRule;
  getAiGeneratedRulesByOrg = aiFns.getAiGeneratedRulesByOrg;
  getAiGeneratedRulesByIncident = aiFns.getAiGeneratedRulesByIncident;
  getAiGeneratedRule = aiFns.getAiGeneratedRule;
  updateAiGeneratedRule = aiFns.updateAiGeneratedRule;
  getEngineConfigs = aiFns.getEngineConfigs;
  getEngineConfig = aiFns.getEngineConfig;
  upsertEngineConfig = aiFns.upsertEngineConfig;
  createEngineDryRun = aiFns.createEngineDryRun;
  getEngineDryRuns = aiFns.getEngineDryRuns;
  updateEngineDryRun = aiFns.updateEngineDryRun;
  createEngineExplainabilityLog = aiFns.createEngineExplainabilityLog;
  getEngineExplainabilityLogs = aiFns.getEngineExplainabilityLogs;
  createAttackGraph = aiFns.createAttackGraph;
  getAttackGraphsByIncident = aiFns.getAttackGraphsByIncident;
  getAttackGraphsByOrg = aiFns.getAttackGraphsByOrg;
  getAttackGraph = aiFns.getAttackGraph;
  deleteAttackGraph = aiFns.deleteAttackGraph;
  createAttackGraphNodes = aiFns.createAttackGraphNodes;
  createAttackGraphEdges = aiFns.createAttackGraphEdges;
  getAttackGraphNodes = aiFns.getAttackGraphNodes;
  getAttackGraphEdges = aiFns.getAttackGraphEdges;

  // ioc
  getIocFeeds = iocFns.getIocFeeds;
  getIocFeed = iocFns.getIocFeed;
  createIocFeed = iocFns.createIocFeed;
  updateIocFeed = iocFns.updateIocFeed;
  deleteIocFeed = iocFns.deleteIocFeed;
  getIocEntries = iocFns.getIocEntries;
  getIocEntry = iocFns.getIocEntry;
  getIocEntriesByValue = iocFns.getIocEntriesByValue;
  createIocEntry = iocFns.createIocEntry;
  createIocEntries = iocFns.createIocEntries;
  updateIocEntry = iocFns.updateIocEntry;
  deleteIocEntry = iocFns.deleteIocEntry;
  getIocWatchlists = iocFns.getIocWatchlists;
  getIocWatchlist = iocFns.getIocWatchlist;
  createIocWatchlist = iocFns.createIocWatchlist;
  updateIocWatchlist = iocFns.updateIocWatchlist;
  deleteIocWatchlist = iocFns.deleteIocWatchlist;
  addIocToWatchlist = iocFns.addIocToWatchlist;
  removeIocFromWatchlist = iocFns.removeIocFromWatchlist;
  getWatchlistEntries = iocFns.getWatchlistEntries;
  getIocMatchRules = iocFns.getIocMatchRules;
  getIocMatchRule = iocFns.getIocMatchRule;
  createIocMatchRule = iocFns.createIocMatchRule;
  updateIocMatchRule = iocFns.updateIocMatchRule;
  deleteIocMatchRule = iocFns.deleteIocMatchRule;
  getIocMatches = iocFns.getIocMatches;
  createIocMatch = iocFns.createIocMatch;

  // cspm
  getCspmAccounts = cspmFns.getCspmAccounts;
  getCspmAccount = cspmFns.getCspmAccount;
  createCspmAccount = cspmFns.createCspmAccount;
  updateCspmAccount = cspmFns.updateCspmAccount;
  deleteCspmAccount = cspmFns.deleteCspmAccount;
  getCspmScans = cspmFns.getCspmScans;
  createCspmScan = cspmFns.createCspmScan;
  updateCspmScan = cspmFns.updateCspmScan;
  getCspmFindings = cspmFns.getCspmFindings;
  createCspmFinding = cspmFns.createCspmFinding;
  updateCspmFinding = cspmFns.updateCspmFinding;
  getCspmDriftBaselines = cspmFns.getCspmDriftBaselines;
  createCspmDriftBaseline = cspmFns.createCspmDriftBaseline;
  deleteCspmDriftBaselines = cspmFns.deleteCspmDriftBaselines;
  getCspmDriftEvents = cspmFns.getCspmDriftEvents;
  createCspmDriftEvent = cspmFns.createCspmDriftEvent;
  updateCspmDriftEvent = cspmFns.updateCspmDriftEvent;
  getCspmDspmFindings = cspmFns.getCspmDspmFindings;
  createCspmDspmFinding = cspmFns.createCspmDspmFinding;
  updateCspmDspmFinding = cspmFns.updateCspmDspmFinding;
  getCspmAttackPaths = cspmFns.getCspmAttackPaths;
  createCspmAttackPath = cspmFns.createCspmAttackPath;
  updateCspmAttackPath = cspmFns.updateCspmAttackPath;
  getCspmRemediations = cspmFns.getCspmRemediations;
  getCspmRemediation = cspmFns.getCspmRemediation;
  createCspmRemediation = cspmFns.createCspmRemediation;
  updateCspmRemediation = cspmFns.updateCspmRemediation;

  // dashboard
  getDashboardStats = dashboardFns.getDashboardStats;
  getDashboardAnalytics = dashboardFns.getDashboardAnalytics;
  getCachedMetrics = dashboardFns.getCachedMetrics;
  upsertCachedMetrics = dashboardFns.upsertCachedMetrics;
  clearExpiredCache = dashboardFns.clearExpiredCache;

  // predictive
  getPredictiveAnomalies = predictiveFns.getPredictiveAnomalies;
  createPredictiveAnomaly = predictiveFns.createPredictiveAnomaly;
  clearPredictiveAnomalies = predictiveFns.clearPredictiveAnomalies;
  getAttackSurfaceAssets = predictiveFns.getAttackSurfaceAssets;
  upsertAttackSurfaceAsset = predictiveFns.upsertAttackSurfaceAsset;
  clearAttackSurfaceAssets = predictiveFns.clearAttackSurfaceAssets;
  getRiskForecasts = predictiveFns.getRiskForecasts;
  createRiskForecast = predictiveFns.createRiskForecast;
  clearRiskForecasts = predictiveFns.clearRiskForecasts;
  getAnomalySubscriptions = predictiveFns.getAnomalySubscriptions;
  createAnomalySubscription = predictiveFns.createAnomalySubscription;
  updateAnomalySubscription = predictiveFns.updateAnomalySubscription;
  deleteAnomalySubscription = predictiveFns.deleteAnomalySubscription;
  getForecastQualitySnapshots = predictiveFns.getForecastQualitySnapshots;
  createForecastQualitySnapshot = predictiveFns.createForecastQualitySnapshot;
  getHardeningRecommendations = predictiveFns.getHardeningRecommendations;
  createHardeningRecommendation = predictiveFns.createHardeningRecommendation;
  updateHardeningRecommendation = predictiveFns.updateHardeningRecommendation;
  clearHardeningRecommendations = predictiveFns.clearHardeningRecommendations;

  // jobs
  getJobs = jobsFns.getJobs;
  getJob = jobsFns.getJob;
  createJob = jobsFns.createJob;
  claimNextJob = jobsFns.claimNextJob;
  updateJob = jobsFns.updateJob;
  cancelJob = jobsFns.cancelJob;
  getJobStats = jobsFns.getJobStats;
  cleanupCompletedJobs = jobsFns.cleanupCompletedJobs;
  createOutboxEvent = jobsFns.createOutboxEvent;
  getPendingOutboxEvents = jobsFns.getPendingOutboxEvents;
  updateOutboxEvent = jobsFns.updateOutboxEvent;
  getOutboxEvent = jobsFns.getOutboxEvent;
  getOutboxEvents = jobsFns.getOutboxEvents;
  replayOutboxEvent = jobsFns.replayOutboxEvent;
  cleanupDispatchedOutboxEvents = jobsFns.cleanupDispatchedOutboxEvents;
  getSliMetrics = jobsFns.getSliMetrics;
  createSliMetric = jobsFns.createSliMetric;
  createSliMetricsBatch = jobsFns.createSliMetricsBatch;
  cleanupOldSliMetrics = jobsFns.cleanupOldSliMetrics;
  getSloTargets = jobsFns.getSloTargets;
  getSloTarget = jobsFns.getSloTarget;
  createSloTarget = jobsFns.createSloTarget;
  updateSloTarget = jobsFns.updateSloTarget;
  deleteSloTarget = jobsFns.deleteSloTarget;
  getDrRunbooks = jobsFns.getDrRunbooks;
  getDrRunbook = jobsFns.getDrRunbook;
  getDrRunbookForOrg = jobsFns.getDrRunbookForOrg;
  createDrRunbook = jobsFns.createDrRunbook;
  updateDrRunbook = jobsFns.updateDrRunbook;
  deleteDrRunbook = jobsFns.deleteDrRunbook;
  getDrDrillResults = jobsFns.getDrDrillResults;
  getDrDrillResult = jobsFns.getDrDrillResult;
  createDrDrillResult = jobsFns.createDrDrillResult;
  updateDrDrillResult = jobsFns.updateDrDrillResult;
  getTicketSyncJobs = jobsFns.getTicketSyncJobs;
  getTicketSyncJob = jobsFns.getTicketSyncJob;
  createTicketSyncJob = jobsFns.createTicketSyncJob;
  updateTicketSyncJob = jobsFns.updateTicketSyncJob;
  deleteTicketSyncJob = jobsFns.deleteTicketSyncJob;

  // response-actions
  getResponseActions = responseActionsFns.getResponseActions;
  getResponseAction = responseActionsFns.getResponseAction;
  createResponseAction = responseActionsFns.createResponseAction;
  updateResponseAction = responseActionsFns.updateResponseAction;
  getAutoResponsePolicies = responseActionsFns.getAutoResponsePolicies;
  getAutoResponsePolicy = responseActionsFns.getAutoResponsePolicy;
  createAutoResponsePolicy = responseActionsFns.createAutoResponsePolicy;
  updateAutoResponsePolicy = responseActionsFns.updateAutoResponsePolicy;
  deleteAutoResponsePolicy = responseActionsFns.deleteAutoResponsePolicy;
  getInvestigationRuns = responseActionsFns.getInvestigationRuns;
  getInvestigationRun = responseActionsFns.getInvestigationRun;
  createInvestigationRun = responseActionsFns.createInvestigationRun;
  updateInvestigationRun = responseActionsFns.updateInvestigationRun;
  getInvestigationSteps = responseActionsFns.getInvestigationSteps;
  createInvestigationStep = responseActionsFns.createInvestigationStep;
  updateInvestigationStep = responseActionsFns.updateInvestigationStep;
  getResponseActionRollbacks = responseActionsFns.getResponseActionRollbacks;
  getResponseActionRollback = responseActionsFns.getResponseActionRollback;
  createResponseActionRollback = responseActionsFns.createResponseActionRollback;
  updateResponseActionRollback = responseActionsFns.updateResponseActionRollback;
  getResponseActionApprovals = responseActionsFns.getResponseActionApprovals;
  getResponseActionApproval = responseActionsFns.getResponseActionApproval;
  createResponseActionApproval = responseActionsFns.createResponseActionApproval;
  updateResponseActionApproval = responseActionsFns.updateResponseActionApproval;

  // reports
  getReportTemplates = reportsFns.getReportTemplates;
  getReportTemplate = reportsFns.getReportTemplate;
  createReportTemplate = reportsFns.createReportTemplate;
  updateReportTemplate = reportsFns.updateReportTemplate;
  deleteReportTemplate = reportsFns.deleteReportTemplate;
  getReportSchedules = reportsFns.getReportSchedules;
  getReportSchedule = reportsFns.getReportSchedule;
  createReportSchedule = reportsFns.createReportSchedule;
  updateReportSchedule = reportsFns.updateReportSchedule;
  deleteReportSchedule = reportsFns.deleteReportSchedule;
  getReportRuns = reportsFns.getReportRuns;
  getReportRun = reportsFns.getReportRun;
  createReportRun = reportsFns.createReportRun;
  updateReportRun = reportsFns.updateReportRun;
  getDueSchedules = reportsFns.getDueSchedules;
  getReportTemplateVersions = reportsFns.getReportTemplateVersions;
  getReportTemplateVersion = reportsFns.getReportTemplateVersion;
  getLatestTemplateVersion = reportsFns.getLatestTemplateVersion;
  createReportTemplateVersion = reportsFns.createReportTemplateVersion;
  updateReportTemplateVersion = reportsFns.updateReportTemplateVersion;

  // billing
  getPlans = billingFns.getPlans;
  getPlan = billingFns.getPlan;
  getPlanByName = billingFns.getPlanByName;
  createPlan = billingFns.createPlan;
  updatePlan = billingFns.updatePlan;
  getSubscription = billingFns.getSubscription;
  getSubscriptionById = billingFns.getSubscriptionById;
  getSubscriptionByStripeCustomerId = billingFns.getSubscriptionByStripeCustomerId;
  getSubscriptionByStripeSubId = billingFns.getSubscriptionByStripeSubId;
  createSubscription = billingFns.createSubscription;
  updateSubscription = billingFns.updateSubscription;
  getInvoices = billingFns.getInvoices;
  getInvoiceByStripeId = billingFns.getInvoiceByStripeId;
  createInvoice = billingFns.createInvoice;
  updateInvoice = billingFns.updateInvoice;
  getUsageRecord = billingFns.getUsageRecord;
  getUsageRecords = billingFns.getUsageRecords;
  incrementUsage = billingFns.incrementUsage;
  resetUsagePeriod = billingFns.resetUsagePeriod;
  countActiveConnectors = billingFns.countActiveConnectors;
  countActiveApiKeys = billingFns.countActiveApiKeys;
  countActivePlaybooks = billingFns.countActivePlaybooks;
  getUsageMeterSnapshots = billingFns.getUsageMeterSnapshots;
  createUsageMeterSnapshot = billingFns.createUsageMeterSnapshot;

  // war-room
  createWarRoom = warRoomFns.createWarRoom;
  getWarRooms = warRoomFns.getWarRooms;
  getWarRoom = warRoomFns.getWarRoom;
  updateWarRoom = warRoomFns.updateWarRoom;
  addWarRoomParticipant = warRoomFns.addWarRoomParticipant;
  getWarRoomParticipants = warRoomFns.getWarRoomParticipants;
  getWarRoomParticipantByUser = warRoomFns.getWarRoomParticipantByUser;
  removeWarRoomParticipant = warRoomFns.removeWarRoomParticipant;
  createWarRoomMessage = warRoomFns.createWarRoomMessage;
  getWarRoomMessages = warRoomFns.getWarRoomMessages;
  getWarRoomMessagesByType = warRoomFns.getWarRoomMessagesByType;
  createWarRoomActionItem = warRoomFns.createWarRoomActionItem;
  getWarRoomActionItems = warRoomFns.getWarRoomActionItems;
  getWarRoomActionItem = warRoomFns.getWarRoomActionItem;
  updateWarRoomActionItem = warRoomFns.updateWarRoomActionItem;
  createWarRoomHandoff = warRoomFns.createWarRoomHandoff;
  getWarRoomHandoffs = warRoomFns.getWarRoomHandoffs;
  getWarRoomHandoff = warRoomFns.getWarRoomHandoff;
  updateWarRoomHandoff = warRoomFns.updateWarRoomHandoff;

  // evidence
  getEvidenceItems = evidenceFns.getEvidenceItems;
  getEvidenceItem = evidenceFns.getEvidenceItem;
  createEvidenceItem = evidenceFns.createEvidenceItem;
  deleteEvidenceItem = evidenceFns.deleteEvidenceItem;
  getHypotheses = evidenceFns.getHypotheses;
  getHypothesis = evidenceFns.getHypothesis;
  createHypothesis = evidenceFns.createHypothesis;
  updateHypothesis = evidenceFns.updateHypothesis;
  deleteHypothesis = evidenceFns.deleteHypothesis;
  getInvestigationTasks = evidenceFns.getInvestigationTasks;
  getInvestigationTask = evidenceFns.getInvestigationTask;
  createInvestigationTask = evidenceFns.createInvestigationTask;
  updateInvestigationTask = evidenceFns.updateInvestigationTask;
  deleteInvestigationTask = evidenceFns.deleteInvestigationTask;
  getEvidenceChainEntries = evidenceFns.getEvidenceChainEntries;
  getEvidenceChainEntriesByOrg = evidenceFns.getEvidenceChainEntriesByOrg;
  countEvidenceChainEntriesByOrg = evidenceFns.countEvidenceChainEntriesByOrg;
  getEvidenceChainEntry = evidenceFns.getEvidenceChainEntry;
  createEvidenceChainEntry = evidenceFns.createEvidenceChainEntry;
  getNextSequenceNum = evidenceFns.getNextSequenceNum;
  getLatestChainHash = evidenceFns.getLatestChainHash;

  // audit
  createAuditLog = auditFns.createAuditLog;
  getAuditLogs = auditFns.getAuditLogs;
  getAuditLogsByResource = auditFns.getAuditLogsByResource;
  getAuditLogCount = auditFns.getAuditLogCount;
  getOldestAuditLog = auditFns.getOldestAuditLog;
  getLatestAuditLogSequence = auditFns.getLatestAuditLogSequence;
  getAuditLogsPaginated = auditFns.getAuditLogsPaginated;

  // notifications
  getNotificationChannels = notificationsFns.getNotificationChannels;
  getNotificationChannel = notificationsFns.getNotificationChannel;
  createNotificationChannel = notificationsFns.createNotificationChannel;
  updateNotificationChannel = notificationsFns.updateNotificationChannel;
  deleteNotificationChannel = notificationsFns.deleteNotificationChannel;
  getNotificationUserPreferences = notificationsFns.getNotificationUserPreferences;
  upsertNotificationUserPreferences = notificationsFns.upsertNotificationUserPreferences;
  createNotificationDeliveryLog = notificationsFns.createNotificationDeliveryLog;
  getNotificationDeliveryLog = notificationsFns.getNotificationDeliveryLog;

  // misc
  getTags = miscFns.getTags;
  createTag = miscFns.createTag;
  deleteTag = miscFns.deleteTag;
  createIngestionLog = miscFns.createIngestionLog;
  getIngestionLogs = miscFns.getIngestionLogs;
  getIngestionLogsPaginated = miscFns.getIngestionLogsPaginated;
  getIngestionStats = miscFns.getIngestionStats;
  getThreatIntelConfigs = miscFns.getThreatIntelConfigs;
  getThreatIntelConfig = miscFns.getThreatIntelConfig;
  upsertThreatIntelConfig = miscFns.upsertThreatIntelConfig;
  deleteThreatIntelConfig = miscFns.deleteThreatIntelConfig;
  getIntegrationConfigs = miscFns.getIntegrationConfigs;
  getIntegrationConfig = miscFns.getIntegrationConfig;
  createIntegrationConfig = miscFns.createIntegrationConfig;
  updateIntegrationConfig = miscFns.updateIntegrationConfig;
  deleteIntegrationConfig = miscFns.deleteIntegrationConfig;
  getOutboundWebhooks = miscFns.getOutboundWebhooks;
  getOutboundWebhook = miscFns.getOutboundWebhook;
  createOutboundWebhook = miscFns.createOutboundWebhook;
  updateOutboundWebhook = miscFns.updateOutboundWebhook;
  deleteOutboundWebhook = miscFns.deleteOutboundWebhook;
  getActiveWebhooksByEvent = miscFns.getActiveWebhooksByEvent;
  getOutboundWebhookLogs = miscFns.getOutboundWebhookLogs;
  createOutboundWebhookLog = miscFns.createOutboundWebhookLog;
  getSuppressionRules = miscFns.getSuppressionRules;
  getSuppressionRule = miscFns.getSuppressionRule;
  createSuppressionRule = miscFns.createSuppressionRule;
  updateSuppressionRule = miscFns.updateSuppressionRule;
  deleteSuppressionRule = miscFns.deleteSuppressionRule;
  listFeatureFlags = miscFns.listFeatureFlags;
  getFeatureFlag = miscFns.getFeatureFlag;
  getFeatureFlagById = miscFns.getFeatureFlagById;
  createFeatureFlag = miscFns.createFeatureFlag;
  updateFeatureFlag = miscFns.updateFeatureFlag;
  deleteFeatureFlag = miscFns.deleteFeatureFlag;
  getSavedViews = miscFns.getSavedViews;
  getSavedView = miscFns.getSavedView;
  createSavedView = miscFns.createSavedView;
  updateSavedView = miscFns.updateSavedView;
  deleteSavedView = miscFns.deleteSavedView;
  getRunbookTemplates = miscFns.getRunbookTemplates;
  getRunbookTemplate = miscFns.getRunbookTemplate;
  createRunbookTemplate = miscFns.createRunbookTemplate;
  updateRunbookTemplate = miscFns.updateRunbookTemplate;
  deleteRunbookTemplate = miscFns.deleteRunbookTemplate;
  getRunbookSteps = miscFns.getRunbookSteps;
  createRunbookStep = miscFns.createRunbookStep;
  updateRunbookStep = miscFns.updateRunbookStep;
  deleteRunbookStep = miscFns.deleteRunbookStep;
  getEndpointAssets = miscFns.getEndpointAssets;
  getEndpointAsset = miscFns.getEndpointAsset;
  createEndpointAsset = miscFns.createEndpointAsset;
  updateEndpointAsset = miscFns.updateEndpointAsset;
  deleteEndpointAsset = miscFns.deleteEndpointAsset;
  getEndpointTelemetry = miscFns.getEndpointTelemetry;
  createEndpointTelemetry = miscFns.createEndpointTelemetry;
  getPostureScores = miscFns.getPostureScores;
  createPostureScore = miscFns.createPostureScore;
  getLatestPostureScore = miscFns.getLatestPostureScore;
  countTableRows = miscFns.countTableRows;

  // sensors & detection
  getNativeSensors = sensorsFns.getNativeSensors;
  getNativeSensor = sensorsFns.getNativeSensor;
  createNativeSensor = sensorsFns.createNativeSensor;
  updateNativeSensor = sensorsFns.updateNativeSensor;
  deleteNativeSensor = sensorsFns.deleteNativeSensor;
  countNativeSensors = sensorsFns.countNativeSensors;
  getDetectionRules = sensorsFns.getDetectionRules;
  getDetectionRule = sensorsFns.getDetectionRule;
  createDetectionRule = sensorsFns.createDetectionRule;
  updateDetectionRule = sensorsFns.updateDetectionRule;
  deleteDetectionRule = sensorsFns.deleteDetectionRule;
  countDetectionRules = sensorsFns.countDetectionRules;
  getSensorEvents = sensorsFns.getSensorEvents;
  getSensorEventsBySensor = sensorsFns.getSensorEventsBySensor;
  createSensorEvent = sensorsFns.createSensorEvent;
  countSensorEvents = sensorsFns.countSensorEvents;
  getDetectionAlerts = sensorsFns.getDetectionAlerts;
  getDetectionAlertsByRule = sensorsFns.getDetectionAlertsByRule;
  createDetectionAlert = sensorsFns.createDetectionAlert;
  countDetectionAlerts = sensorsFns.countDetectionAlerts;
  countDetectionAlertsByRule = sensorsFns.countDetectionAlertsByRule;

  // dark web
  getDarkWebExposures = darkWebFns.getDarkWebExposures;
  getDarkWebExposure = darkWebFns.getDarkWebExposure;
  createDarkWebExposure = darkWebFns.createDarkWebExposure;
  updateDarkWebExposure = darkWebFns.updateDarkWebExposure;
  deleteDarkWebExposure = darkWebFns.deleteDarkWebExposure;
  countDarkWebExposures = darkWebFns.countDarkWebExposures;
  countDarkWebExposuresByStatus = darkWebFns.countDarkWebExposuresByStatus;
  getDarkWebMonitoringConfig = darkWebFns.getDarkWebMonitoringConfig;
  upsertDarkWebMonitoringConfig = darkWebFns.upsertDarkWebMonitoringConfig;
  getDarkWebScanHistory = darkWebFns.getDarkWebScanHistory;
  createDarkWebScanHistoryEntry = darkWebFns.createDarkWebScanHistoryEntry;
  updateDarkWebScanHistoryEntry = darkWebFns.updateDarkWebScanHistoryEntry;

  // collectors
  getCollectorInstances = collectorsFns.getCollectorInstances;
  getCollectorInstance = collectorsFns.getCollectorInstance;
  createCollectorInstance = collectorsFns.createCollectorInstance;
  updateCollectorInstance = collectorsFns.updateCollectorInstance;
  deleteCollectorInstance = collectorsFns.deleteCollectorInstance;
  countCollectorInstances = collectorsFns.countCollectorInstances;
  getCollectorEvents = collectorsFns.getCollectorEvents;
  getCollectorEventsByInstance = collectorsFns.getCollectorEventsByInstance;
  createCollectorEvent = collectorsFns.createCollectorEvent;
  countCollectorEvents = collectorsFns.countCollectorEvents;
  getCollectorScans = collectorsFns.getCollectorScans;
  createCollectorScan = collectorsFns.createCollectorScan;
  updateCollectorScan = collectorsFns.updateCollectorScan;

  // chaos engineering
  getChaosSimulations = chaosFns.getChaosSimulations;
  getChaosSimulation = chaosFns.getChaosSimulation;
  createChaosSimulation = chaosFns.createChaosSimulation;
  updateChaosSimulation = chaosFns.updateChaosSimulation;
  deleteChaosSimulation = chaosFns.deleteChaosSimulation;
  countChaosSimulations = chaosFns.countChaosSimulations;
  getChaosSchedules = chaosFns.getChaosSchedules;
  getChaosSchedule = chaosFns.getChaosSchedule;
  createChaosSchedule = chaosFns.createChaosSchedule;
  updateChaosSchedule = chaosFns.updateChaosSchedule;
  deleteChaosSchedule = chaosFns.deleteChaosSchedule;

  // dns security
  getDnsEvents = dnsFns.getDnsEvents;
  createDnsEvent = dnsFns.createDnsEvent;
  countDnsEvents = dnsFns.countDnsEvents;
  countSuspiciousDnsEvents = dnsFns.countSuspiciousDnsEvents;
  getDnsFindings = dnsFns.getDnsFindings;
  getDnsFinding = dnsFns.getDnsFinding;
  createDnsFinding = dnsFns.createDnsFinding;
  updateDnsFinding = dnsFns.updateDnsFinding;
  countDnsFindings = dnsFns.countDnsFindings;
  countDnsFindingsByStatus = dnsFns.countDnsFindingsByStatus;
  getPassiveDnsRecords = dnsFns.getPassiveDnsRecords;
  getPassiveDnsRecordsByDomain = dnsFns.getPassiveDnsRecordsByDomain;
  createPassiveDnsRecord = dnsFns.createPassiveDnsRecord;
  countPassiveDnsRecords = dnsFns.countPassiveDnsRecords;

  // security graph
  getSecurityGraphAssets = securityGraphFns.getSecurityGraphAssets;
  getSecurityGraphAssetsByType = securityGraphFns.getSecurityGraphAssetsByType;
  getSecurityGraphAsset = securityGraphFns.getSecurityGraphAsset;
  getSecurityGraphAssetByResolutionKey = securityGraphFns.getSecurityGraphAssetByResolutionKey;
  createSecurityGraphAsset = securityGraphFns.createSecurityGraphAsset;
  updateSecurityGraphAsset = securityGraphFns.updateSecurityGraphAsset;
  deleteSecurityGraphAsset = securityGraphFns.deleteSecurityGraphAsset;
  countSecurityGraphAssets = securityGraphFns.countSecurityGraphAssets;
  getSecurityGraphRelationships = securityGraphFns.getSecurityGraphRelationships;
  getSecurityGraphRelationship = securityGraphFns.getSecurityGraphRelationship;
  getSecurityGraphRelationshipsByAsset = securityGraphFns.getSecurityGraphRelationshipsByAsset;
  createSecurityGraphRelationship = securityGraphFns.createSecurityGraphRelationship;
  deleteSecurityGraphRelationship = securityGraphFns.deleteSecurityGraphRelationship;
  countSecurityGraphRelationships = securityGraphFns.countSecurityGraphRelationships;

  // trust center
  getTrustCenterArtifacts = trustCenterFns.getTrustCenterArtifacts;
  getTrustCenterArtifact = trustCenterFns.getTrustCenterArtifact;
  createTrustCenterArtifact = trustCenterFns.createTrustCenterArtifact;
  updateTrustCenterArtifact = trustCenterFns.updateTrustCenterArtifact;
  deleteTrustCenterArtifact = trustCenterFns.deleteTrustCenterArtifact;
  countTrustCenterArtifacts = trustCenterFns.countTrustCenterArtifacts;
  getTrustCenterDownloads = trustCenterFns.getTrustCenterDownloads;
  createTrustCenterDownload = trustCenterFns.createTrustCenterDownload;
  countTrustCenterDownloads = trustCenterFns.countTrustCenterDownloads;

  // policy packs
  getPolicyPackActivations = policyPacksFns.getPolicyPackActivations;
  getPolicyPackActivation = policyPacksFns.getPolicyPackActivation;
  getPolicyPackActivationById = policyPacksFns.getPolicyPackActivationById;
  createPolicyPackActivation = policyPacksFns.createPolicyPackActivation;
  updatePolicyPackActivation = policyPacksFns.updatePolicyPackActivation;
  deletePolicyPackActivation = policyPacksFns.deletePolicyPackActivation;
  countPolicyPackActivations = policyPacksFns.countPolicyPackActivations;

  // marketplace
  getMarketplaceInstances = marketplaceFns.getMarketplaceInstances;
  getMarketplaceInstance = marketplaceFns.getMarketplaceInstance;
  createMarketplaceInstance = marketplaceFns.createMarketplaceInstance;
  updateMarketplaceInstance = marketplaceFns.updateMarketplaceInstance;
  deleteMarketplaceInstance = marketplaceFns.deleteMarketplaceInstance;
  countMarketplaceInstances = marketplaceFns.countMarketplaceInstances;
  getMarketplaceWebhookEvents = marketplaceFns.getMarketplaceWebhookEvents;
  createMarketplaceWebhookEvent = marketplaceFns.createMarketplaceWebhookEvent;
  getMarketplaceDeadLetters = marketplaceFns.getMarketplaceDeadLetters;
  getMarketplaceDeadLetter = marketplaceFns.getMarketplaceDeadLetter;
  createMarketplaceDeadLetter = marketplaceFns.createMarketplaceDeadLetter;
  updateMarketplaceDeadLetter = marketplaceFns.updateMarketplaceDeadLetter;
  getMarketplaceSyncHistory = marketplaceFns.getMarketplaceSyncHistory;
  createMarketplaceSyncHistoryEntry = marketplaceFns.createMarketplaceSyncHistoryEntry;
  updateMarketplaceSyncHistoryEntry = marketplaceFns.updateMarketplaceSyncHistoryEntry;

  // cross-cutting
  getCrossCuttingEvidenceList = crossCuttingFns.getCrossCuttingEvidenceList;
  getCrossCuttingEvidenceItem = crossCuttingFns.getCrossCuttingEvidenceItem;
  createCrossCuttingEvidenceItem = crossCuttingFns.createCrossCuttingEvidenceItem;
  updateCrossCuttingEvidenceItem = crossCuttingFns.updateCrossCuttingEvidenceItem;
  countCrossCuttingEvidence = crossCuttingFns.countCrossCuttingEvidence;
  getCrossCuttingDriftRecords = crossCuttingFns.getCrossCuttingDriftRecords;
  getCrossCuttingDriftRecord = crossCuttingFns.getCrossCuttingDriftRecord;
  createCrossCuttingDriftRecord = crossCuttingFns.createCrossCuttingDriftRecord;
  updateCrossCuttingDriftRecord = crossCuttingFns.updateCrossCuttingDriftRecord;
  countCrossCuttingDrift = crossCuttingFns.countCrossCuttingDrift;
  getCrossCuttingOverrides = crossCuttingFns.getCrossCuttingOverrides;
  getCrossCuttingOverride = crossCuttingFns.getCrossCuttingOverride;
  createCrossCuttingOverride = crossCuttingFns.createCrossCuttingOverride;
  updateCrossCuttingOverride = crossCuttingFns.updateCrossCuttingOverride;
  deleteCrossCuttingOverride = crossCuttingFns.deleteCrossCuttingOverride;
  countCrossCuttingOverrides = crossCuttingFns.countCrossCuttingOverrides;

  // jit access
  getJitAccessRequests = jitAccessFns.getJitAccessRequests;
  getJitAccessRequest = jitAccessFns.getJitAccessRequest;
  getJitAccessRequestsByRequester = jitAccessFns.getJitAccessRequestsByRequester;
  createJitAccessRequest = jitAccessFns.createJitAccessRequest;
  updateJitAccessRequest = jitAccessFns.updateJitAccessRequest;
  countJitAccessRequests = jitAccessFns.countJitAccessRequests;
  countPendingJitAccessRequests = jitAccessFns.countPendingJitAccessRequests;

  // adversarial testing
  getAdversarialExecutions = adversarialTestingFns.getAdversarialExecutions;
  getAdversarialExecution = adversarialTestingFns.getAdversarialExecution;
  createAdversarialExecution = adversarialTestingFns.createAdversarialExecution;
  updateAdversarialExecution = adversarialTestingFns.updateAdversarialExecution;
  countAdversarialExecutions = adversarialTestingFns.countAdversarialExecutions;
  getAdversarialSchedules = adversarialTestingFns.getAdversarialSchedules;
  getAdversarialSchedule = adversarialTestingFns.getAdversarialSchedule;
  createAdversarialSchedule = adversarialTestingFns.createAdversarialSchedule;
  updateAdversarialSchedule = adversarialTestingFns.updateAdversarialSchedule;
  deleteAdversarialSchedule = adversarialTestingFns.deleteAdversarialSchedule;
  getAdversarialRemediations = adversarialTestingFns.getAdversarialRemediations;
  getAdversarialRemediation = adversarialTestingFns.getAdversarialRemediation;
  createAdversarialRemediation = adversarialTestingFns.createAdversarialRemediation;
  updateAdversarialRemediation = adversarialTestingFns.updateAdversarialRemediation;

  // agent tool security
  getAgentToolInvocations = agentToolSecurityFns.getAgentToolInvocations;
  getAgentToolInvocation = agentToolSecurityFns.getAgentToolInvocation;
  createAgentToolInvocation = agentToolSecurityFns.createAgentToolInvocation;
  countAgentToolInvocations = agentToolSecurityFns.countAgentToolInvocations;
  getAgentToolAnomalies = agentToolSecurityFns.getAgentToolAnomalies;
  acknowledgeAgentToolAnomaly = agentToolSecurityFns.acknowledgeAgentToolAnomaly;
  createAgentToolAnomaly = agentToolSecurityFns.createAgentToolAnomaly;
  countAgentToolAnomalies = agentToolSecurityFns.countAgentToolAnomalies;
  getAgentToolPoliciesList = agentToolSecurityFns.getAgentToolPoliciesList;
  getAgentToolPolicyByTool = agentToolSecurityFns.getAgentToolPolicyByTool;
  upsertAgentToolPolicy = agentToolSecurityFns.upsertAgentToolPolicy;
  getAgentTrustBoundaryRulesList = agentToolSecurityFns.getAgentTrustBoundaryRulesList;
  getAgentTrustBoundaryRule = agentToolSecurityFns.getAgentTrustBoundaryRule;
  createAgentTrustBoundaryRule = agentToolSecurityFns.createAgentTrustBoundaryRule;
  updateAgentTrustBoundaryRule = agentToolSecurityFns.updateAgentTrustBoundaryRule;
  deleteAgentTrustBoundaryRule = agentToolSecurityFns.deleteAgentTrustBoundaryRule;

  // browser defense
  getBrowserSessions = browserDefenseFns.getBrowserSessions;
  getBrowserSession = browserDefenseFns.getBrowserSession;
  createBrowserSession = browserDefenseFns.createBrowserSession;
  updateBrowserSession = browserDefenseFns.updateBrowserSession;
  countBrowserSessions = browserDefenseFns.countBrowserSessions;
  getBrowserEgressRules = browserDefenseFns.getBrowserEgressRules;
  getBrowserEgressRule = browserDefenseFns.getBrowserEgressRule;
  createBrowserEgressRule = browserDefenseFns.createBrowserEgressRule;
  updateBrowserEgressRule = browserDefenseFns.updateBrowserEgressRule;
  deleteBrowserEgressRule = browserDefenseFns.deleteBrowserEgressRule;
  getBrowserTrustedPaths = browserDefenseFns.getBrowserTrustedPaths;
  getBrowserTrustedPath = browserDefenseFns.getBrowserTrustedPath;
  createBrowserTrustedPath = browserDefenseFns.createBrowserTrustedPath;
  updateBrowserTrustedPath = browserDefenseFns.updateBrowserTrustedPath;
  deleteBrowserTrustedPath = browserDefenseFns.deleteBrowserTrustedPath;

  // runtime guardrails
  getRuntimePolicies = runtimeGuardrailsFns.getRuntimePolicies;
  getRuntimePolicy = runtimeGuardrailsFns.getRuntimePolicy;
  createRuntimePolicy = runtimeGuardrailsFns.createRuntimePolicy;
  updateRuntimePolicy = runtimeGuardrailsFns.updateRuntimePolicy;
  deleteRuntimePolicy = runtimeGuardrailsFns.deleteRuntimePolicy;
  countRuntimePolicies = runtimeGuardrailsFns.countRuntimePolicies;
  getRuntimeDecisions = runtimeGuardrailsFns.getRuntimeDecisions;
  createRuntimeDecision = runtimeGuardrailsFns.createRuntimeDecision;
  countRuntimeDecisions = runtimeGuardrailsFns.countRuntimeDecisions;
  getRuntimeOverrides = runtimeGuardrailsFns.getRuntimeOverrides;
  getRuntimeOverride = runtimeGuardrailsFns.getRuntimeOverride;
  createRuntimeOverride = runtimeGuardrailsFns.createRuntimeOverride;
  updateRuntimeOverride = runtimeGuardrailsFns.updateRuntimeOverride;
}

export const storage = new DatabaseStorage();
